# No Show Prediction

In [68]:
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
from sklearn import metrics
from pandas.api.types import CategoricalDtype
import pyMechkar as pyMechkar
from pyMechkar import analysis

In [69]:
# Train df
df = pd.read_csv("c:/Users/Mayer/Documents/DataScience/project/Noshows/NoShowTrain.csv")
dftest = pd.read_csv("c:/Users/Mayer/Documents/DataScience/project/Noshows/NoShowTest.csv")

In [70]:
df.head()

NoShow  sunday  monday  saturday  time_booked  service_CAL  service_CALC  \
0       0       0       0         0         1050            0             0   
1       0       0       0         0          690            0             0   
2       0       0       0         0         1080            0             0   
3       0       0       0         0          800            0             0   
4       1       1       0         0          780            0             0   

   service_CAS  service_CBAL  service_CCAMO  ...  total_cancel12  hclust3_1  \
0            0             0              0  ...               0          0   
1            0             0              0  ...               0          1   
2            0             0              0  ...               0          0   
3            0             0              0  ...               1          0   
4            0             0              0  ...               0          1   

   hclust4_4  Mclust3_1  Mclust3_2  Mclust3_3  Mclust4_1  Mclust4_2  \
0          0          0          1          0          0          1   
1          0          0          1          0          0          0   
2          0          0          1          0          0          1   
3          1          0          1          0          0          1   
4          0          1          0          0          1          0   

   Mclust4_3  Mclust4_4  
0          0          0  
1          1          0  
2          0          0  
3          0          0  
4          0          0  

[5 rows x 57 columns]

In [71]:
df.describe()

NoShow       sunday       monday     saturday  time_booked  \
count  1310.000000  1310.000000  1310.000000  1310.000000  1310.000000   
mean      0.083969     0.028244     0.000763     0.204580   803.923664   
std       0.277448     0.165733     0.027629     0.403549   174.371801   
min       0.000000     0.000000     0.000000     0.000000   480.000000   
25%       0.000000     0.000000     0.000000     0.000000   660.000000   
50%       0.000000     0.000000     0.000000     0.000000   790.000000   
75%       0.000000     0.000000     0.000000     0.000000   950.000000   
max       1.000000     1.000000     1.000000     1.000000  1170.000000   

       service_CAL  service_CALC  service_CAS  service_CBAL  service_CCAMO  \
count  1310.000000   1310.000000       1310.0   1310.000000    1310.000000   
mean      0.003053      0.020611          0.0      0.009924       0.010687   
std       0.055195      0.142131          0.0      0.099160       0.102863   
min       0.000000      0.000000          0.0      0.000000       0.000000   
25%       0.000000      0.000000          0.0      0.000000       0.000000   
50%       0.000000      0.000000          0.0      0.000000       0.000000   
75%       0.000000      0.000000          0.0      0.000000       0.000000   
max       1.000000      1.000000          0.0      1.000000       1.000000   

       ...  total_cancel12    hclust3_1    hclust4_4    Mclust3_1  \
count  ...     1310.000000  1310.000000  1310.000000  1310.000000   
mean   ...        0.463359     0.447328     0.226718     0.209160   
std    ...        0.890379     0.497408     0.418868     0.406864   
min    ...        0.000000     0.000000     0.000000     0.000000   
25%    ...        0.000000     0.000000     0.000000     0.000000   
50%    ...        0.000000     0.000000     0.000000     0.000000   
75%    ...        1.000000     1.000000     0.000000     0.000000   
max    ...        4.000000     1.000000     1.000000     1.000000   

         Mclust3_2    Mclust3_3    Mclust4_1    Mclust4_2    Mclust4_3  \
count  1310.000000  1310.000000  1310.000000  1310.000000  1310.000000   
mean      0.658015     0.132824     0.209160     0.357252     0.300763   
std       0.474556     0.339514     0.406864     0.479373     0.458765   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       1.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     0.000000     1.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

         Mclust4_4  
count  1310.000000  
mean      0.132824  
std       0.339514  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       1.000000  

[8 rows x 57 columns]

In [72]:
dftest.describe()

NoShow      sunday  monday    saturday  time_booked  service_CAL  \
count  874.000000  874.000000   874.0  874.000000   874.000000   874.000000   
mean     0.069794    0.032037     0.0    0.185355   805.926773     0.002288   
std      0.254946    0.176198     0.0    0.388808   178.000538     0.047809   
min      0.000000    0.000000     0.0    0.000000   480.000000     0.000000   
25%      0.000000    0.000000     0.0    0.000000   660.000000     0.000000   
50%      0.000000    0.000000     0.0    0.000000   800.000000     0.000000   
75%      0.000000    0.000000     0.0    0.000000   960.000000     0.000000   
max      1.000000    1.000000     0.0    1.000000  1150.000000     1.000000   

       service_CALC  service_CAS  service_CBAL  service_CCAMO  ...  \
count    874.000000   874.000000    874.000000     874.000000  ...   
mean       0.014874     0.001144      0.012586       0.005721  ...   
std        0.121118     0.033826      0.111542       0.075463  ...   
min        0.000000     0.000000      0.000000       0.000000  ...   
25%        0.000000     0.000000      0.000000       0.000000  ...   
50%        0.000000     0.000000      0.000000       0.000000  ...   
75%        0.000000     0.000000      0.000000       0.000000  ...   
max        1.000000     1.000000      1.000000       1.000000  ...   

       total_cancel12   hclust3_1   hclust4_4   Mclust3_1   Mclust3_2  \
count      874.000000  874.000000  874.000000  874.000000  874.000000   
mean         0.503432    0.440503    0.212815    0.208238    0.679634   
std          0.943106    0.496732    0.409532    0.406280    0.466884   
min          0.000000    0.000000    0.000000    0.000000    0.000000   
25%          0.000000    0.000000    0.000000    0.000000    0.000000   
50%          0.000000    0.000000    0.000000    0.000000    1.000000   
75%          1.000000    1.000000    0.000000    0.000000    1.000000   
max          4.000000    1.000000    1.000000    1.000000    1.000000   

        Mclust3_3   Mclust4_1   Mclust4_2   Mclust4_3   Mclust4_4  
count  874.000000  874.000000  874.000000  874.000000  874.000000  
mean     0.112128    0.208238    0.372998    0.306636    0.112128  
std      0.315705    0.406280    0.483878    0.461361    0.315705  
min      0.000000    0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000    0.000000    0.000000  
75%      0.000000    0.000000    1.000000    1.000000    0.000000  
max      1.000000    1.000000    1.000000    1.000000    1.000000  

[8 rows x 57 columns]

In [73]:
df2 = df.copy()
df2.dtypes[df.columns[0:1]]
df2['NoShow'] = df2['NoShow'].astype('category')

In [74]:
dftest2 = dftest.copy()
dftest2.dtypes[df.columns[0:1]]
dftest2['NoShow'] = dftest2['NoShow'].astype('category')

In [75]:
X_train = df2.iloc[:,1:48]
nc_ = df2.iloc[:,48:57] #clusters
y_train = df2.NoShow

In [76]:
X_test = dftest2.iloc[:,1:48]
y_test = dftest2.NoShow

In [77]:
X_train.head()

sunday  monday  saturday  time_booked  service_CAL  service_CALC  \
0       0       0         0         1050            0             0   
1       0       0         0          690            0             0   
2       0       0         0         1080            0             0   
3       0       0         0          800            0             0   
4       1       0         0          780            0             0   

   service_CAS  service_CBAL  service_CCAMO  service_CCO  ...  quantity_1  \
0            0             0              0            0  ...           0   
1            0             0              0            0  ...           0   
2            0             0              0            0  ...           0   
3            0             0              0            0  ...           0   
4            0             0              0            0  ...           0   

   quantity_2  quantity_5  quantity_6  quantity_7    amount  avg_receipt_4  \
0           1           0           0           0  3.433987              0   
1           1           0           0           0  4.634729              0   
2           1           0           0           0  3.583519              1   
3           1           0           0           0  3.931826              1   
4           0           0           0           1  0.000000              0   

   avg_receipt_5  avg_quantity_5  total_cancel12  
0              0               0               0  
1              0               0               0  
2              0               0               0  
3              0               0               1  
4              0               0               0  

[5 rows x 47 columns]

In [78]:
y_train.head()

0    0
1    0
2    0
3    0
4    1
Name: NoShow, dtype: category
Categories (2, int64): [0, 1]

# Metric Selection

In [79]:
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer


### Logistic Regression

In [80]:
from sklearn.linear_model import LogisticRegression

In [81]:
mod1 = LogisticRegression()
mod1.fit(X_train,y_train)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [82]:
yhat1 = mod1.predict(X_train)
yhat1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [83]:
yprob1 = mod1.predict_proba(X_train)
yprob1

array([[0.98171473, 0.01828527],
       [0.98642713, 0.01357287],
       [0.97085749, 0.02914251],
       ...,
       [0.98680588, 0.01319412],
       [0.99048016, 0.00951984],
       [0.98616698, 0.01383302]])

In [84]:
pd.crosstab(y_train,yhat1)

C:\Users\Mayer\Anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:277: FutureWarning: Categorical.ravel will return a Categorical object instead of an ndarray in a future version.
  vec = libmissing.isnaobj_old(values.ravel())


col_0      0   1
NoShow          
0       1186  14
1         68  42

In [85]:
### AUC - without CV:
print('AUC= %f' % roc_auc_score(y_train,yhat1))

# metrics with CV
scoring = {'ROC_AUC': 'roc_auc',
           'F1': make_scorer(f1_score, average='binary'),
           'F1_weighted': make_scorer(f1_score, average='weighted')}
scores = cross_validate(mod1, X_train, y_train, scoring=scoring,
                        cv=4, return_train_score=True)
sorted(scores.keys())

AUC= 0.685076


C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


['fit_time',
 'score_time',
 'test_F1',
 'test_F1_weighted',
 'test_ROC_AUC',
 'train_F1',
 'train_F1_weighted',
 'train_ROC_AUC']

In [86]:
#sklearn.metrics.SCORERS.keys()

In [87]:
yhat2 = mod1.predict(X_test)

In [88]:
scores_test = cross_validate(mod1, X_test, y_test, scoring=scoring,
                        cv=4, return_train_score=True)
sorted(scores_test.keys())


C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


['fit_time',
 'score_time',
 'test_F1',
 'test_F1_weighted',
 'test_ROC_AUC',
 'train_F1',
 'train_F1_weighted',
 'train_ROC_AUC']

In [89]:
### AUC
print(scores['train_ROC_AUC'])
print(scores_test['train_ROC_AUC'])

[0.95302846 0.9451897  0.95627845 0.96087684]
[0.92508666 0.9288489  0.91594797 0.93661796]


In [90]:
### F1 Score
print(scores['train_F1'])
print(scores_test['train_F1'])

[0.53225806 0.45       0.57142857 0.53968254]
[0.31034483 0.36065574 0.27586207 0.14545455]


In [91]:
### F1_weighted Score
print(scores['train_F1_weighted'])
print(scores_test['train_F1_weighted'])

[0.93205254 0.92127028 0.93534249 0.93227272]
[0.9227485  0.92617893 0.91807779 0.9053089 ]


We can clearly see that <b> roc_auc </b>and<b> f1-weight </b>(taking imbalance into account) are better then f1 

In [92]:
scoring = {'ROC_AUC': 'roc_auc',
           'F1_weighted': make_scorer(f1_score, average='weighted')}

## CV strategy Selection

Some classification problems can exhibit a large imbalance in the distribution of the target classes: for instance there could be several times more negative samples than positive samples. In such cases it is recommended to use stratified sampling as implemented in StratifiedKFold and StratifiedShuffleSplit to ensure that relative class frequencies is approximately preserved in each train and validation fold.

In [93]:
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.model_selection import StratifiedShuffleSplit

In [94]:
skf = StratifiedKFold(n_splits=3, shuffle=False, random_state=952)

skf.split(X_train, y_train)


<generator object _BaseKFold.split at 0x0000022D706012A0>

In [95]:
sss = StratifiedShuffleSplit(n_splits=3, test_size=0.5, random_state=952)
sss.split(X_train, y_train)

<generator object BaseShuffleSplit.split at 0x0000022D70601CF0>

In [96]:
from  sklearn.linear_model import LogisticRegressionCV

In [97]:
mod1 = LogisticRegressionCV(cv=skf,solver='liblinear',random_state=952).fit(X_train,y_train)
mod2 = LogisticRegressionCV(cv=sss,solver='liblinear',random_state=952).fit(X_train,y_train)

In [98]:
scores_skf = cross_validate(mod1, X_train, y_train, scoring=scoring, return_train_score=True)
scores_sss = cross_validate(mod2, X_train, y_train, scoring=scoring, return_train_score=True)
print('ROC_AUC')
print(scores_skf['train_ROC_AUC'])
print(scores_sss['train_ROC_AUC'])

print('F1-Weighted')
print(scores_skf['train_F1_weighted'])
print(scores_sss['train_F1_weighted'])

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


ROC_AUC
[0.9388613  0.95785959 0.98006757]
[0.96142979 0.96558219 0.98006757]
F1-Weighted
[0.92012182 0.93230628 0.95373851]
[0.93364079 0.94316651 0.95373851]


I will use <b>StratifiedShuffleSplit</b> as Corss validation startegy

# Cross  Validation Models

### LogisticReggressionCV

In [99]:
#mod1 = LogisticRegressionCV(cv=sss,solver='liblinear',random_state=383).fit(X_train,y_train)
mod1 = LogisticRegressionCV(random_state=383).fit(X_train,y_train)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the n

In [100]:
scores_lr = cross_validate(mod1, X_train, y_train, scoring=scoring, return_train_score=True)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: Convergen

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", Convergenc

In [101]:
#res = {'Logistic Regression':{
#           'AUC-train':scores_lr['train_ROC_AUC'],
#           'AUC-test':scores_lr['test_ROC_AUC'],
#           'F1_W-train':scores_lr['train_F1_weighted'],
#           'F1_W-test' : scores_lr['test_F1_weighted']
#          
#      }}

In [102]:
res = {'Name':'Logistic Regression',
        'Model':'mod1',
        'AUC-train':scores_lr['train_ROC_AUC'],
        'AUC-test':scores_lr['test_ROC_AUC'],
        'F1_W-train':scores_lr['train_F1_weighted'],
        'F1_W-test' : scores_lr['test_F1_weighted']
          
      }
res = pd.DataFrame(res)

### ComplementNB 

It is particularly suited for imbalanced data sets.

In [103]:
#from sklearn.linear_model import ElasticNetCV
from sklearn.naive_bayes import ComplementNB

In [104]:
mod2 = ComplementNB().fit(X_train,y_train)

In [105]:
scores_CNB = cross_validate(mod2, X_train, y_train, scoring=scoring, return_train_score=True)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [106]:
#res ['ComplementNB'] = {
#           'AUC-train':scores_CNB['train_ROC_AUC'],
#           'AUC-test':scores_CNB['test_ROC_AUC'],
#           'F1_W-train':scores_CNB['train_F1_weighted'],
#           'F1_W-test' : scores_CNB['test_F1_weighted']
#          
#      }

In [107]:
res2 = {'Name':'ComplementNB',
        'Model':'mod2',
        'AUC-train':scores_CNB['train_ROC_AUC'],
        'AUC-test':scores_CNB['test_ROC_AUC'],
        'F1_W-train':scores_CNB['train_F1_weighted'],
        'F1_W-test' : scores_CNB['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

### Support Vector Machine Classifaier (SVC)

In [108]:
from sklearn.svm import SVC

In [109]:
#mod3 = SVC(gamma = 'scale',kernel = 'sigmoid', class_weight = 'balanced',random_state=383).fit(X_train,y_train)
mod3 = SVC(random_state=383).fit(X_train,y_train)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [110]:
scores_SVC = cross_validate(mod3, X_train, y_train,  scoring=scoring, return_train_score=True)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'p

In [111]:
res2 = {'Name':'SVC',
        'Model':'mod3',
        'AUC-train':scores_SVC['train_ROC_AUC'],
        'AUC-test':scores_SVC['test_ROC_AUC'],
        'F1_W-train':scores_SVC['train_F1_weighted'],
        'F1_W-test' : scores_SVC['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

### Classification Trees

In [112]:
from sklearn.tree import DecisionTreeClassifier

#mod4 = DecisionTreeClassifier(random_state=383, class_weight = 'balanced').fit(X_train,y_train)
mod4 = DecisionTreeClassifier(random_state=383).fit(X_train,y_train)

scores_DTC = cross_validate(mod4, X_train, y_train, scoring=scoring, return_train_score=True)

res2 = {'Name':'Decision Tree Classifier',
        'Model':'mod4',
        'AUC-train':scores_DTC['train_ROC_AUC'],
        'AUC-test':scores_DTC['test_ROC_AUC'],
        'F1_W-train':scores_DTC['train_F1_weighted'],
        'F1_W-test' : scores_DTC['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


### Random Forest

In [113]:
from sklearn.ensemble import RandomForestClassifier

#mod5 = RandomForestClassifier(random_state=383, class_weight = 'balanced').fit(X_train,y_train)
mod5 = RandomForestClassifier(random_state=383).fit(X_train,y_train)

scores_rf = cross_validate(mod5, X_train, y_train, scoring=scoring, return_train_score=True)

res2 = {'Name':'Random Forest Classifier',
        'Model':'mod5',
        'AUC-train':scores_rf['train_ROC_AUC'],
        'AUC-test':scores_rf['test_ROC_AUC'],
        'F1_W-train':scores_rf['train_F1_weighted'],
        'F1_W-test' : scores_rf['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


### ADAboost

In [114]:
from sklearn.ensemble import AdaBoostClassifier

mod6 = AdaBoostClassifier(random_state=383).fit(X_train,y_train)

scores_ADA = cross_validate(mod6, X_train, y_train, scoring=scoring, return_train_score=True)

res2 = {'Name':'ADAboost',
        'Model':'mod6',
        'AUC-train':scores_ADA['train_ROC_AUC'],
        'AUC-test':scores_ADA['test_ROC_AUC'],
        'F1_W-train':scores_ADA['train_F1_weighted'],
        'F1_W-test' : scores_ADA['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


### eXtreme Gradient Boosting (XGboost)

In [115]:
from xgboost import XGBClassifier
from xgboost import cv
from xgboost import DMatrix

weights = {0: 1, 1: 3}
#dtrain = DMatrix(np.array(X_train), label=y_train,weight = weights)
#params = {'max_depth':3, 'eta':1, 'objective':"reg:logistic"}

#mod7 = XGBClassifier(objective='reg:logistic',random_state=383)
mod7 = XGBClassifier(random_state=383)

scores_XGB = cross_validate(mod7, X_train, y_train, scoring=scoring, return_train_score=True)

res2 = {'Name':'XGboost',
        'Model':'mod7',
        'AUC-train':scores_XGB['train_ROC_AUC'],
        'AUC-test':scores_XGB['test_ROC_AUC'],
        'F1_W-train':scores_XGB['train_F1_weighted'],
        'F1_W-test' : scores_XGB['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


### GradientBoostingClassifier

In [116]:
from sklearn.ensemble import GradientBoostingClassifier

mod8 = GradientBoostingClassifier(random_state=383).fit(X_train,y_train)

scores_GBC = cross_validate(mod8, X_train, y_train, scoring=scoring, return_train_score=True)

res2 = {'Name':'Gradient Boosting Classifier',
        'Model':'mod8',
        'AUC-train':scores_GBC['train_ROC_AUC'],
        'AUC-test':scores_GBC['test_ROC_AUC'],
        'F1_W-train':scores_GBC['train_F1_weighted'],
        'F1_W-test' : scores_GBC['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


## Results

In [117]:
res.insert(4,'AUC_diff',abs(res['AUC-train']-res['AUC-test']))
res.insert(7,'F1_W_diff',abs(res['F1_W-train']-res['F1_W-test']))
res

Name Model  AUC-train  AUC-test  AUC_diff  \
0           Logistic Regression  mod1   0.963416  0.947635  0.015781   
1           Logistic Regression  mod1   0.965908  0.950777  0.015131   
2           Logistic Regression  mod1   0.980777  0.914792  0.065985   
0                  ComplementNB  mod2   0.930522  0.901486  0.029036   
1                  ComplementNB  mod2   0.927277  0.948412  0.021135   
2                  ComplementNB  mod2   0.944257  0.898889  0.045368   
0                           SVC  mod3   0.993296  0.765068  0.228229   
1                           SVC  mod3   0.997568  0.684831  0.312737   
2                           SVC  mod3   0.991858  0.749861  0.241997   
0      Decision Tree Classifier  mod4   0.999991  0.685709  0.314282   
1      Decision Tree Classifier  mod4   0.999966  0.716959  0.283006   
2      Decision Tree Classifier  mod4   0.999983  0.669444  0.330539   
0      Random Forest Classifier  mod5   0.999829  0.932128  0.067700   
1      Random Forest Classifier  mod5   0.999675  0.904493  0.095181   
2      Random Forest Classifier  mod5   0.999814  0.855625  0.144189   
0                      ADAboost  mod6   0.970308  0.955068  0.015241   
1                      ADAboost  mod6   0.972808  0.952432  0.020376   
2                      ADAboost  mod6   0.984215  0.855208  0.129006   
0                       XGboost  mod7   0.999923  0.937297  0.062626   
1                       XGboost  mod7   0.999966  0.939155  0.060810   
2                       XGboost  mod7   0.999983  0.902708  0.097275   
0  Gradient Boosting Classifier  mod8   0.992046  0.941453  0.050594   
1  Gradient Boosting Classifier  mod8   0.990745  0.930912  0.059833   
2  Gradient Boosting Classifier  mod8   0.995448  0.924653  0.070795   

   F1_W-train  F1_W-test  F1_W_diff  
0    0.936840   0.922554   0.014286  
1    0.945535   0.933225   0.012309  
2    0.955388   0.912235   0.043153  
0    0.870132   0.861248   0.008884  
1    0.880299   0.882072   0.001773  
2    0.882695   0.856134   0.026561  
0    0.876395   0.874869   0.001526  
1    0.879179   0.874869   0.004310  
2    0.888208   0.876779   0.011429  
0    0.998851   0.914809   0.084042  
1    0.997695   0.911294   0.086400  
2    0.998852   0.902414   0.096439  
0    0.991852   0.895016   0.096836  
1    0.989454   0.912014   0.077439  
2    0.991809   0.908176   0.083633  
0    0.942991   0.921505   0.021487  
1    0.939485   0.933225   0.006260  
2    0.955798   0.896050   0.059748  
0    0.996553   0.918860   0.077693  
1    0.997695   0.928620   0.069074  
2    0.998852   0.909548   0.089304  
0    0.978215   0.917042   0.061172  
1    0.977260   0.933225   0.044035  
2    0.979691   0.903075   0.076616

In [118]:
res.sort_values(by='AUC-test',ascending=False)

Name Model  AUC-train  AUC-test  AUC_diff  \
0                      ADAboost  mod6   0.970308  0.955068  0.015241   
1                      ADAboost  mod6   0.972808  0.952432  0.020376   
1           Logistic Regression  mod1   0.965908  0.950777  0.015131   
1                  ComplementNB  mod2   0.927277  0.948412  0.021135   
0           Logistic Regression  mod1   0.963416  0.947635  0.015781   
0  Gradient Boosting Classifier  mod8   0.992046  0.941453  0.050594   
1                       XGboost  mod7   0.999966  0.939155  0.060810   
0                       XGboost  mod7   0.999923  0.937297  0.062626   
0      Random Forest Classifier  mod5   0.999829  0.932128  0.067700   
1  Gradient Boosting Classifier  mod8   0.990745  0.930912  0.059833   
2  Gradient Boosting Classifier  mod8   0.995448  0.924653  0.070795   
2           Logistic Regression  mod1   0.980777  0.914792  0.065985   
1      Random Forest Classifier  mod5   0.999675  0.904493  0.095181   
2                       XGboost  mod7   0.999983  0.902708  0.097275   
0                  ComplementNB  mod2   0.930522  0.901486  0.029036   
2                  ComplementNB  mod2   0.944257  0.898889  0.045368   
2      Random Forest Classifier  mod5   0.999814  0.855625  0.144189   
2                      ADAboost  mod6   0.984215  0.855208  0.129006   
0                           SVC  mod3   0.993296  0.765068  0.228229   
2                           SVC  mod3   0.991858  0.749861  0.241997   
1      Decision Tree Classifier  mod4   0.999966  0.716959  0.283006   
0      Decision Tree Classifier  mod4   0.999991  0.685709  0.314282   
1                           SVC  mod3   0.997568  0.684831  0.312737   
2      Decision Tree Classifier  mod4   0.999983  0.669444  0.330539   

   F1_W-train  F1_W-test  F1_W_diff  
0    0.942991   0.921505   0.021487  
1    0.939485   0.933225   0.006260  
1    0.945535   0.933225   0.012309  
1    0.880299   0.882072   0.001773  
0    0.936840   0.922554   0.014286  
0    0.978215   0.917042   0.061172  
1    0.997695   0.928620   0.069074  
0    0.996553   0.918860   0.077693  
0    0.991852   0.895016   0.096836  
1    0.977260   0.933225   0.044035  
2    0.979691   0.903075   0.076616  
2    0.955388   0.912235   0.043153  
1    0.989454   0.912014   0.077439  
2    0.998852   0.909548   0.089304  
0    0.870132   0.861248   0.008884  
2    0.882695   0.856134   0.026561  
2    0.991809   0.908176   0.083633  
2    0.955798   0.896050   0.059748  
0    0.876395   0.874869   0.001526  
2    0.888208   0.876779   0.011429  
1    0.997695   0.911294   0.086400  
0    0.998851   0.914809   0.084042  
1    0.879179   0.874869   0.004310  
2    0.998852   0.902414   0.096439

In [119]:
res.sort_values(by='F1_W-test',ascending=False)

Name Model  AUC-train  AUC-test  AUC_diff  \
1  Gradient Boosting Classifier  mod8   0.990745  0.930912  0.059833   
1                      ADAboost  mod6   0.972808  0.952432  0.020376   
1           Logistic Regression  mod1   0.965908  0.950777  0.015131   
1                       XGboost  mod7   0.999966  0.939155  0.060810   
0           Logistic Regression  mod1   0.963416  0.947635  0.015781   
0                      ADAboost  mod6   0.970308  0.955068  0.015241   
0                       XGboost  mod7   0.999923  0.937297  0.062626   
0  Gradient Boosting Classifier  mod8   0.992046  0.941453  0.050594   
0      Decision Tree Classifier  mod4   0.999991  0.685709  0.314282   
2           Logistic Regression  mod1   0.980777  0.914792  0.065985   
1      Random Forest Classifier  mod5   0.999675  0.904493  0.095181   
1      Decision Tree Classifier  mod4   0.999966  0.716959  0.283006   
2                       XGboost  mod7   0.999983  0.902708  0.097275   
2      Random Forest Classifier  mod5   0.999814  0.855625  0.144189   
2  Gradient Boosting Classifier  mod8   0.995448  0.924653  0.070795   
2      Decision Tree Classifier  mod4   0.999983  0.669444  0.330539   
2                      ADAboost  mod6   0.984215  0.855208  0.129006   
0      Random Forest Classifier  mod5   0.999829  0.932128  0.067700   
1                  ComplementNB  mod2   0.927277  0.948412  0.021135   
2                           SVC  mod3   0.991858  0.749861  0.241997   
1                           SVC  mod3   0.997568  0.684831  0.312737   
0                           SVC  mod3   0.993296  0.765068  0.228229   
0                  ComplementNB  mod2   0.930522  0.901486  0.029036   
2                  ComplementNB  mod2   0.944257  0.898889  0.045368   

   F1_W-train  F1_W-test  F1_W_diff  
1    0.977260   0.933225   0.044035  
1    0.939485   0.933225   0.006260  
1    0.945535   0.933225   0.012309  
1    0.997695   0.928620   0.069074  
0    0.936840   0.922554   0.014286  
0    0.942991   0.921505   0.021487  
0    0.996553   0.918860   0.077693  
0    0.978215   0.917042   0.061172  
0    0.998851   0.914809   0.084042  
2    0.955388   0.912235   0.043153  
1    0.989454   0.912014   0.077439  
1    0.997695   0.911294   0.086400  
2    0.998852   0.909548   0.089304  
2    0.991809   0.908176   0.083633  
2    0.979691   0.903075   0.076616  
2    0.998852   0.902414   0.096439  
2    0.955798   0.896050   0.059748  
0    0.991852   0.895016   0.096836  
1    0.880299   0.882072   0.001773  
2    0.888208   0.876779   0.011429  
1    0.879179   0.874869   0.004310  
0    0.876395   0.874869   0.001526  
0    0.870132   0.861248   0.008884  
2    0.882695   0.856134   0.026561

AUC-test score shows that the best model by both score and diffrance between train score to test score is <b> ADAboost </b>

# ADAboost Fine-Tuning

In [123]:
#from sklearn.metrics import mean_squared_error, mean_absolute_error
#from sklearn.metrics import score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

We will use <b> Random Search </b> for the fine tuning of the model

In [124]:
#def evaluate (model, X,y):
#    y_hat = model.predict(X)
#    AUC = roc_auc_score(y,y_hat)
#    
#    print('Model Performance')
#    print('AUC = {:0.4f}'.format(AUC))
#        
#    return [AUC]

#### Run base model

In [125]:
mod6 = AdaBoostClassifier(random_state=383).fit(X_train,y_train)
y_hat = mod6.predict(X_train)

#mod6_AUC = evaluate (mod6, X_test,y_test)

# Return the mean accuracy on the given test data
#base_score = mod6.score(X_train, y_hat)
base_AUC = cross_validate(mod6, X_train, y_hat, scoring='roc_auc',cv=sss, return_train_score=False)

base_res = {'Base Score':base_AUC['test_score']}
base_res = pd.DataFrame(base_res)
base_res


Base Score
0    0.967917
1    0.969182
2    0.942010

Hayperparameter Fine-Tuning

In [126]:
# The maximum number of estimators at which boosting is terminated
n_estimators = [int(x) for x in np.linspace(start=10, stop=1000, num=15)]
# Learning rate shrinks the contribution
learning_rate = [1e-6,1e-1,5e-2,1e-2,5e-3,1e-3,5e-4,1e-4,5e-5,1e-5,5e-6,1]
# Boosting algorithm
algorithm = ['SAMME', 'SAMME.R']

random_grid = {'n_estimators': n_estimators,
               'learning_rate': learning_rate,
               'algorithm': algorithm}

print(random_grid)

{'n_estimators': [10, 80, 151, 222, 292, 363, 434, 504, 575, 646, 717, 787, 858, 929, 1000], 'learning_rate': [1e-06, 0.1, 0.05, 0.01, 0.005, 0.001, 0.0005, 0.0001, 5e-05, 1e-05, 5e-06, 1], 'algorithm': ['SAMME', 'SAMME.R']}


In [127]:
ab = AdaBoostClassifier()

ab_random = RandomizedSearchCV(estimator = ab, param_distributions = random_grid, n_iter = 100, cv = sss,
                               verbose=2, random_state = 383, n_jobs=-1)

# Fit the random search model
ab_random.fit(X_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   32.9s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  3.6min finished


RandomizedSearchCV(cv=StratifiedShuffleSplit(n_splits=3, random_state=952, test_size=0.5,
            train_size=None),
                   error_score='raise-deprecating',
                   estimator=AdaBoostClassifier(algorithm='SAMME.R',
                                                base_estimator=None,
                                                learning_rate=1.0,
                                                n_estimators=50,
                                                random_state=None),
                   iid='warn', n_iter=100, n_jobs=-1,
                   param_distributions={'algorithm': ['SAMME', 'SAMME.R'],
                                        'learning_rate': [1e-06, 0.1, 0.05,
                                                          0.01, 0.005, 0.001,
                                                          0.0005, 0.0001, 5e-05,
                                                          1e-05, 5e-06, 1],
                                        'n_estimat

In [128]:
ab_random.best_params_

{'n_estimators': 575, 'learning_rate': 0.05, 'algorithm': 'SAMME.R'}

In [129]:
best_random = ab_random.best_estimator_
yhat = best_random.predict(X_train)

random_AUC = cross_validate(best_random, X_train, y_hat, scoring='roc_auc',cv=sss, return_train_score=False)
#random_score = best_random.score(X_test, y_test)

random_res = {'Base Score':base_AUC['test_score'],
              'Random Score':random_AUC['test_score']
      }
random_res = pd.DataFrame(random_res)
random_res

Base Score  Random Score
0    0.967917      0.992135
1    0.969182      0.982311
2    0.942010      0.982153

<b>Grid Search</b> : We decide which parameters and how (not randomly)

In [130]:
# Create the parameter grid
param_grid = {'n_estimators': [400,500,600],
               'learning_rate': [0.01, 0.05, 0.1],
               'algorithm': ['SAMME.R']
}

grid_search = GridSearchCV(estimator = ab, param_grid = param_grid, cv = sss,
                           verbose=2, n_jobs=-1)

In [131]:
# Fit the grid search to the data
grid_search.fit(X_train,y_train)

Fitting 3 folds for each of 9 candidates, totalling 27 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  27 out of  27 | elapsed:   25.0s finished


GridSearchCV(cv=StratifiedShuffleSplit(n_splits=3, random_state=952, test_size=0.5,
            train_size=None),
             error_score='raise-deprecating',
             estimator=AdaBoostClassifier(algorithm='SAMME.R',
                                          base_estimator=None,
                                          learning_rate=1.0, n_estimators=50,
                                          random_state=None),
             iid='warn', n_jobs=-1,
             param_grid={'algorithm': ['SAMME.R'],
                         'learning_rate': [0.01, 0.05, 0.1],
                         'n_estimators': [400, 500, 600]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=2)

In [132]:
grid_search.best_params_

{'algorithm': 'SAMME.R', 'learning_rate': 0.05, 'n_estimators': 600}

In [133]:
#the best parameters
best_grid = grid_search.best_estimator_
y_hat = best_grid.predict(X_train)

grid_AUC = cross_validate(best_grid, X_train, y_hat, scoring='roc_auc',cv=sss, return_train_score=False)
#grid_score = best_grid.score(X_test, y_test)

grid_res = {'Base Score':base_AUC['test_score'],
            'Random Score':random_AUC['test_score'],
            'Grid Score':grid_AUC['test_score']
      }
grid_res = pd.DataFrame(grid_res)
grid_res

Base Score  Random Score  Grid Score
0    0.967917      0.992135    0.997653
1    0.969182      0.982311    0.995994
2    0.942010      0.982153    0.996485

We can see the improvment between base, random and grid fine tuning

# Predict the final results

In [134]:
# make a prediction
y_pred = best_grid.predict(X_test)


In [136]:
pd.crosstab(y_test,y_pred)

col_0     0   1
NoShow         
0       793  20
1        47  14

In [142]:
yprob = best_grid.predict_proba(X_test)
yprob = pd.DataFrame(yprob)
yprob

0         1
0    0.548398  0.451602
1    0.522407  0.477593
2    0.539654  0.460346
3    0.539654  0.460346
4    0.539654  0.460346
..        ...       ...
869  0.547447  0.452553
870  0.547447  0.452553
871  0.540053  0.459947
872  0.550280  0.449720
873  0.543937  0.456063

[874 rows x 2 columns]

## Saving the model

In [143]:
from sklearn.externals import joblib

filename = 'NoShowFinalModel.model'
joblib.dump(best_grid,filename)
             

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


['NoShowFinalModel.model']