# No Show Prediction

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
from sklearn import metrics
from pandas.api.types import CategoricalDtype
import pyMechkar as pyMechkar
from pyMechkar import analysis

In [6]:
# Train df
df = pd.read_csv("c:/Users/Mayer/Documents/DataScience/project/Noshows/NoShowTrain.csv")
dftest = pd.read_csv("c:/Users/Mayer/Documents/DataScience/project/Noshows/NoShowTest.csv")

In [3]:
df.head()

NoShow  sunday  monday  saturday  time_booked  service_CAL  service_CALC  \
0       0       0       0         0         1050            0             0   
1       0       0       0         0          690            0             0   
2       0       0       0         0         1080            0             0   
3       0       0       0         0          800            0             0   
4       1       1       0         0          780            0             0   

   service_CAS  service_CBAL  service_CCAMO  ...  total_cancel12  hclust3_1  \
0            0             0              0  ...               0          0   
1            0             0              0  ...               0          1   
2            0             0              0  ...               0          0   
3            0             0              0  ...               1          0   
4            0             0              0  ...               0          1   

   hclust4_4  Mclust3_1  Mclust3_2  Mclust3_3  Mclust4_1  Mclust4_2  \
0          0          0          1          0          0          1   
1          0          0          1          0          0          0   
2          0          0          1          0          0          1   
3          1          0          1          0          0          1   
4          0          1          0          0          1          0   

   Mclust4_3  Mclust4_4  
0          0          0  
1          1          0  
2          0          0  
3          0          0  
4          0          0  

[5 rows x 57 columns]

In [4]:
df.describe()

NoShow       sunday       monday     saturday  time_booked  \
count  1310.000000  1310.000000  1310.000000  1310.000000  1310.000000   
mean      0.083969     0.028244     0.000763     0.204580   803.923664   
std       0.277448     0.165733     0.027629     0.403549   174.371801   
min       0.000000     0.000000     0.000000     0.000000   480.000000   
25%       0.000000     0.000000     0.000000     0.000000   660.000000   
50%       0.000000     0.000000     0.000000     0.000000   790.000000   
75%       0.000000     0.000000     0.000000     0.000000   950.000000   
max       1.000000     1.000000     1.000000     1.000000  1170.000000   

       service_CAL  service_CALC  service_CAS  service_CBAL  service_CCAMO  \
count  1310.000000   1310.000000       1310.0   1310.000000    1310.000000   
mean      0.003053      0.020611          0.0      0.009924       0.010687   
std       0.055195      0.142131          0.0      0.099160       0.102863   
min       0.000000      0.000000          0.0      0.000000       0.000000   
25%       0.000000      0.000000          0.0      0.000000       0.000000   
50%       0.000000      0.000000          0.0      0.000000       0.000000   
75%       0.000000      0.000000          0.0      0.000000       0.000000   
max       1.000000      1.000000          0.0      1.000000       1.000000   

       ...  total_cancel12    hclust3_1    hclust4_4    Mclust3_1  \
count  ...     1310.000000  1310.000000  1310.000000  1310.000000   
mean   ...        0.463359     0.447328     0.226718     0.209160   
std    ...        0.890379     0.497408     0.418868     0.406864   
min    ...        0.000000     0.000000     0.000000     0.000000   
25%    ...        0.000000     0.000000     0.000000     0.000000   
50%    ...        0.000000     0.000000     0.000000     0.000000   
75%    ...        1.000000     1.000000     0.000000     0.000000   
max    ...        4.000000     1.000000     1.000000     1.000000   

         Mclust3_2    Mclust3_3    Mclust4_1    Mclust4_2    Mclust4_3  \
count  1310.000000  1310.000000  1310.000000  1310.000000  1310.000000   
mean      0.658015     0.132824     0.209160     0.357252     0.300763   
std       0.474556     0.339514     0.406864     0.479373     0.458765   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       1.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     0.000000     1.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

         Mclust4_4  
count  1310.000000  
mean      0.132824  
std       0.339514  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       1.000000  

[8 rows x 57 columns]

In [39]:
dftest.describe()

NoShow      sunday  monday    saturday  time_booked  service_CAL  \
count  874.000000  874.000000   874.0  874.000000   874.000000   874.000000   
mean     0.069794    0.032037     0.0    0.185355   805.926773     0.002288   
std      0.254946    0.176198     0.0    0.388808   178.000538     0.047809   
min      0.000000    0.000000     0.0    0.000000   480.000000     0.000000   
25%      0.000000    0.000000     0.0    0.000000   660.000000     0.000000   
50%      0.000000    0.000000     0.0    0.000000   800.000000     0.000000   
75%      0.000000    0.000000     0.0    0.000000   960.000000     0.000000   
max      1.000000    1.000000     0.0    1.000000  1150.000000     1.000000   

       service_CALC  service_CAS  service_CBAL  service_CCAMO  ...  \
count    874.000000   874.000000    874.000000     874.000000  ...   
mean       0.014874     0.001144      0.012586       0.005721  ...   
std        0.121118     0.033826      0.111542       0.075463  ...   
min        0.000000     0.000000      0.000000       0.000000  ...   
25%        0.000000     0.000000      0.000000       0.000000  ...   
50%        0.000000     0.000000      0.000000       0.000000  ...   
75%        0.000000     0.000000      0.000000       0.000000  ...   
max        1.000000     1.000000      1.000000       1.000000  ...   

       total_cancel12   hclust3_1   hclust4_4   Mclust3_1   Mclust3_2  \
count      874.000000  874.000000  874.000000  874.000000  874.000000   
mean         0.503432    0.440503    0.212815    0.208238    0.679634   
std          0.943106    0.496732    0.409532    0.406280    0.466884   
min          0.000000    0.000000    0.000000    0.000000    0.000000   
25%          0.000000    0.000000    0.000000    0.000000    0.000000   
50%          0.000000    0.000000    0.000000    0.000000    1.000000   
75%          1.000000    1.000000    0.000000    0.000000    1.000000   
max          4.000000    1.000000    1.000000    1.000000    1.000000   

        Mclust3_3   Mclust4_1   Mclust4_2   Mclust4_3   Mclust4_4  
count  874.000000  874.000000  874.000000  874.000000  874.000000  
mean     0.112128    0.208238    0.372998    0.306636    0.112128  
std      0.315705    0.406280    0.483878    0.461361    0.315705  
min      0.000000    0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000    0.000000    0.000000  
75%      0.000000    0.000000    1.000000    1.000000    0.000000  
max      1.000000    1.000000    1.000000    1.000000    1.000000  

[8 rows x 57 columns]

In [22]:
df2 = df.copy()
df2.dtypes[df.columns[0:1]]
df2['NoShow'] = df2['NoShow'].astype('category')

In [23]:
dftest2 = dftest.copy()
dftest2.dtypes[df.columns[0:1]]
dftest2['NoShow'] = dftest2['NoShow'].astype('category')

In [24]:
X_train = df2.iloc[:,1:48]
nc_ = df2.iloc[:,48:57] #clusters
y_train = df2.NoShow

In [25]:
X_test = dftest2.iloc[:,1:48]
y_test = dftest2.NoShow

In [26]:
X_train.head()

sunday  monday  saturday  time_booked  service_CAL  service_CALC  \
0       0       0         0         1050            0             0   
1       0       0         0          690            0             0   
2       0       0         0         1080            0             0   
3       0       0         0          800            0             0   
4       1       0         0          780            0             0   

   service_CAS  service_CBAL  service_CCAMO  service_CCO  ...  quantity_1  \
0            0             0              0            0  ...           0   
1            0             0              0            0  ...           0   
2            0             0              0            0  ...           0   
3            0             0              0            0  ...           0   
4            0             0              0            0  ...           0   

   quantity_2  quantity_5  quantity_6  quantity_7    amount  avg_receipt_4  \
0           1           0           0           0  3.433987              0   
1           1           0           0           0  4.634729              0   
2           1           0           0           0  3.583519              1   
3           1           0           0           0  3.931826              1   
4           0           0           0           1  0.000000              0   

   avg_receipt_5  avg_quantity_5  total_cancel12  
0              0               0               0  
1              0               0               0  
2              0               0               0  
3              0               0               1  
4              0               0               0  

[5 rows x 47 columns]

In [27]:
y_train.head()

0    0
1    0
2    0
3    0
4    1
Name: NoShow, dtype: category
Categories (2, int64): [0, 1]

# Metric Selection

In [28]:
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer


### Logistic Regression

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
mod1 = LogisticRegression()
mod1.fit(X_train,y_train)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
yhat1 = mod1.predict(X_train)
yhat1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [32]:
yprob1 = mod1.predict_proba(X_train)
yprob1

array([[0.98171473, 0.01828527],
       [0.98642713, 0.01357287],
       [0.97085749, 0.02914251],
       ...,
       [0.98680588, 0.01319412],
       [0.99048016, 0.00951984],
       [0.98616698, 0.01383302]])

In [33]:
pd.crosstab(y_train,yhat1)

C:\Users\Mayer\Anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:277: FutureWarning: Categorical.ravel will return a Categorical object instead of an ndarray in a future version.
  vec = libmissing.isnaobj_old(values.ravel())


col_0      0   1
NoShow          
0       1186  14
1         68  42

In [74]:
### AUC - without CV:
print('AUC= %f' % roc_auc_score(y_train,yhat1))

# metrics with CV
scoring = {'ROC_AUC': 'roc_auc',
           'F1': make_scorer(f1_score, average='binary'),
           'F1_weighted': make_scorer(f1_score, average='weighted')}
scores = cross_validate(mod1, X_train, y_train, scoring=scoring,
                        cv=4, return_train_score=True)
sorted(scores.keys())

AUC= 0.685076


C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


['fit_time',
 'score_time',
 'test_F1',
 'test_F1_weighted',
 'test_ROC_AUC',
 'train_F1',
 'train_F1_weighted',
 'train_ROC_AUC']

In [40]:
#sklearn.metrics.SCORERS.keys()

In [40]:
yhat2 = mod1.predict(X_test)

In [72]:
scores_test = cross_validate(mod1, X_test, y_test, scoring=scoring,
                        cv=4, return_train_score=True)
sorted(scores_test.keys())


C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


['fit_time',
 'score_time',
 'test_F1',
 'test_F1_weighted',
 'test_ROC_AUC',
 'train_F1',
 'train_F1_weighted',
 'train_ROC_AUC']

In [67]:
### AUC
print(scores['train_ROC_AUC'])
print(scores_test['train_ROC_AUC'])

[0.95302846 0.9451897  0.95627845 0.96087684]
[0.92508666 0.9288489  0.91594797 0.93661796]


In [71]:
### F1 Score
print(scores['train_F1'])
print(scores_test['train_F1'])

[0.53225806 0.45       0.57142857 0.53968254]
[0.31034483 0.36065574 0.27586207 0.14545455]


In [70]:
### F1_weighted Score
print(scores['train_F1_weighted'])
print(scores_test['train_F1_weighted'])

[0.93205254 0.92127028 0.93534249 0.93227272]
[0.9227485  0.92617893 0.91807779 0.9053089 ]


We can clearly see that <b> roc_auc </b>and<b> f1-weight </b>(taking imbalance into account) are better then f1 

In [86]:
scoring = {'ROC_AUC': 'roc_auc',
           'F1_weighted': make_scorer(f1_score, average='weighted')}

## CV strategy Selection

Some classification problems can exhibit a large imbalance in the distribution of the target classes: for instance there could be several times more negative samples than positive samples. In such cases it is recommended to use stratified sampling as implemented in StratifiedKFold and StratifiedShuffleSplit to ensure that relative class frequencies is approximately preserved in each train and validation fold.

In [35]:
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.model_selection import StratifiedShuffleSplit

In [94]:
skf = StratifiedKFold(n_splits=3, shuffle=False, random_state=952)

skf.split(X_train, y_train)


<generator object _BaseKFold.split at 0x000001C056FB5840>

In [95]:
sss = StratifiedShuffleSplit(n_splits=3, test_size=0.5, random_state=952)
sss.split(X_train, y_train)

<generator object BaseShuffleSplit.split at 0x000001C056FB55E8>

In [96]:
from  sklearn.linear_model import LogisticRegressionCV

In [97]:
mod1 = LogisticRegressionCV(cv=skf,solver='liblinear',random_state=952).fit(X_train,y_train)
mod2 = LogisticRegressionCV(cv=sss,solver='liblinear',random_state=952).fit(X_train,y_train)

In [98]:
scores_skf = cross_validate(mod1, X_train, y_train, scoring=scoring, return_train_score=True)
scores_sss = cross_validate(mod2, X_train, y_train, scoring=scoring, return_train_score=True)
print('ROC_AUC')
print(scores_skf['train_ROC_AUC'])
print(scores_sss['train_ROC_AUC'])

print('F1-Weighted')
print(scores_skf['train_F1_weighted'])
print(scores_sss['train_F1_weighted'])

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


ROC_AUC
[0.9388613  0.95785959 0.98006757]
[0.96142979 0.96558219 0.98006757]
F1-Weighted
[0.92012182 0.93230628 0.95373851]
[0.93364079 0.94316651 0.95373851]


I will use <b>StratifiedShuffleSplit</b> as Corss validation startegy

# Cross  Validation Models

### LogisticReggressionCV

In [361]:
#mod1 = LogisticRegressionCV(cv=sss,solver='liblinear',random_state=383).fit(X_train,y_train)
mod1 = LogisticRegressionCV(cv=sss,random_state=383).fit(X_train,y_train)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", Convergenc

In [362]:
scores_lr = cross_validate(mod1, X_train, y_train, scoring=scoring, return_train_score=True)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the n

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", Convergenc

In [339]:
#res = {'Logistic Regression':{
#           'AUC-train':scores_lr['train_ROC_AUC'],
#           'AUC-test':scores_lr['test_ROC_AUC'],
#           'F1_W-train':scores_lr['train_F1_weighted'],
#           'F1_W-test' : scores_lr['test_F1_weighted']
#          
#      }}

In [393]:
res = {'Name':'Logistic Regression',
        'Model':'mod1',
        'AUC-train':scores_lr['train_ROC_AUC'],
        'AUC-test':scores_lr['test_ROC_AUC'],
        'F1_W-train':scores_lr['train_F1_weighted'],
        'F1_W-test' : scores_lr['test_F1_weighted']
          
      }
res = pd.DataFrame(res)

### ComplementNB 

It is particularly suited for imbalanced data sets.

In [394]:
#from sklearn.linear_model import ElasticNetCV
from sklearn.naive_bayes import ComplementNB

In [395]:
mod2 = ComplementNB().fit(X_train,y_train)

In [396]:
scores_CNB = cross_validate(mod2, X_train, y_train, cv = sss, scoring=scoring, return_train_score=True)

In [397]:
#res ['ComplementNB'] = {
#           'AUC-train':scores_CNB['train_ROC_AUC'],
#           'AUC-test':scores_CNB['test_ROC_AUC'],
#           'F1_W-train':scores_CNB['train_F1_weighted'],
#           'F1_W-test' : scores_CNB['test_F1_weighted']
#          
#      }

In [398]:
res2 = {'Name':'ComplementNB',
        'Model':'mod2',
        'AUC-train':scores_CNB['train_ROC_AUC'],
        'AUC-test':scores_CNB['test_ROC_AUC'],
        'F1_W-train':scores_CNB['train_F1_weighted'],
        'F1_W-test' : scores_CNB['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

### Support Vector Machine Classifaier (SVC)

In [399]:
from sklearn.svm import SVC

In [400]:
#mod3 = SVC(gamma = 'scale',kernel = 'sigmoid', class_weight = 'balanced',random_state=383).fit(X_train,y_train)
mod3 = SVC(random_state=383).fit(X_train,y_train)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [401]:
scores_SVC = cross_validate(mod3, X_train, y_train, cv= 3, scoring=scoring, return_train_score=True)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly 

In [402]:
res2 = {'Name':'SVC',
        'Model':'mod3',
        'AUC-train':scores_SVC['train_ROC_AUC'],
        'AUC-test':scores_SVC['test_ROC_AUC'],
        'F1_W-train':scores_SVC['train_F1_weighted'],
        'F1_W-test' : scores_SVC['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

### Classification Trees

In [403]:
from sklearn.tree import DecisionTreeClassifier

#mod4 = DecisionTreeClassifier(random_state=383, class_weight = 'balanced').fit(X_train,y_train)
od4 = DecisionTreeClassifier(random_state=383).fit(X_train,y_train)

scores_DTC = cross_validate(mod4, X_train, y_train, cv= 3, scoring=scoring, return_train_score=True)

res2 = {'Name':'Decision Tree Classifier',
        'Model':'mod4',
        'AUC-train':scores_DTC['train_ROC_AUC'],
        'AUC-test':scores_DTC['test_ROC_AUC'],
        'F1_W-train':scores_DTC['train_F1_weighted'],
        'F1_W-test' : scores_DTC['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

### Random Forest

In [404]:
from sklearn.ensemble import RandomForestClassifier

#mod5 = RandomForestClassifier(random_state=383, class_weight = 'balanced').fit(X_train,y_train)
mod5 = RandomForestClassifier(random_state=383).fit(X_train,y_train)

scores_rf = cross_validate(mod5, X_train, y_train, cv= 3, scoring=scoring, return_train_score=True)

res2 = {'Name':'Random Forest Classifier',
        'Model':'mod5',
        'AUC-train':scores_rf['train_ROC_AUC'],
        'AUC-test':scores_rf['test_ROC_AUC'],
        'F1_W-train':scores_rf['train_F1_weighted'],
        'F1_W-test' : scores_rf['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


### ADAboost

In [405]:
from sklearn.ensemble import AdaBoostClassifier

mod6 = AdaBoostClassifier(random_state=383).fit(X_train,y_train)

scores_ADA = cross_validate(mod6, X_train, y_train, cv= 3, scoring=scoring, return_train_score=True)

res2 = {'Name':'ADAboost',
        'Model':'mod6',
        'AUC-train':scores_ADA['train_ROC_AUC'],
        'AUC-test':scores_ADA['test_ROC_AUC'],
        'F1_W-train':scores_ADA['train_F1_weighted'],
        'F1_W-test' : scores_ADA['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

### eXtreme Gradient Boosting (XGboost)

In [406]:
from xgboost import XGBClassifier
from xgboost import cv
from xgboost import DMatrix

weights = {0: 1, 1: 3}
#dtrain = DMatrix(np.array(X_train), label=y_train,weight = weights)
#params = {'max_depth':3, 'eta':1, 'objective':"reg:logistic"}

#mod7 = XGBClassifier(objective='reg:logistic',random_state=383)
mod7 = XGBClassifier(random_state=383)

scores_XGB = cross_validate(mod7, X_train, y_train, cv= 3, scoring=scoring, return_train_score=True)

res2 = {'Name':'XGboost',
        'Model':'mod7',
        'AUC-train':scores_XGB['train_ROC_AUC'],
        'AUC-test':scores_XGB['test_ROC_AUC'],
        'F1_W-train':scores_XGB['train_F1_weighted'],
        'F1_W-test' : scores_XGB['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

### GradientBoostingClassifier

In [407]:
from sklearn.ensemble import GradientBoostingClassifier

mod8 = GradientBoostingClassifier(random_state=383).fit(X_train,y_train)

scores_GBC = cross_validate(mod8, X_train, y_train, cv= 3, scoring=scoring, return_train_score=True)

res2 = {'Name':'Gradient Boosting Classifier',
        'Model':'mod8',
        'AUC-train':scores_GBC['train_ROC_AUC'],
        'AUC-test':scores_GBC['test_ROC_AUC'],
        'F1_W-train':scores_GBC['train_F1_weighted'],
        'F1_W-test' : scores_GBC['test_F1_weighted']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

## Results

In [408]:
res.insert(4,'AUC_diff',abs(res['AUC-train']-res['AUC-test']))
res.insert(7,'F1_W_diff',abs(res['F1_W-train']-res['F1_W-test']))
res

Name Model  AUC-train  AUC-test  AUC_diff  \
0           Logistic Regression  mod1   0.963399  0.949595  0.013804   
1           Logistic Regression  mod1   0.939812  0.941385  0.001573   
2           Logistic Regression  mod1   0.979561  0.913056  0.066505   
0                  ComplementNB  mod2   0.923848  0.924788  0.000939   
1                  ComplementNB  mod2   0.922530  0.925318  0.002788   
2                  ComplementNB  mod2   0.929258  0.906727  0.022530   
0                           SVC  mod3   0.993296  0.765068  0.228229   
1                           SVC  mod3   0.997568  0.684831  0.312737   
2                           SVC  mod3   0.991858  0.749861  0.241997   
0      Decision Tree Classifier  mod4   0.999991  0.652568  0.347424   
1      Decision Tree Classifier  mod4   0.999966  0.693007  0.306959   
2      Decision Tree Classifier  mod4   0.999983  0.648056  0.351928   
0      Random Forest Classifier  mod5   0.999829  0.932128  0.067700   
1      Random Forest Classifier  mod5   0.999675  0.904493  0.095181   
2      Random Forest Classifier  mod5   0.999814  0.855625  0.144189   
0                      ADAboost  mod6   0.970308  0.955068  0.015241   
1                      ADAboost  mod6   0.972808  0.952432  0.020376   
2                      ADAboost  mod6   0.984215  0.855208  0.129006   
0                       XGboost  mod7   0.999923  0.937297  0.062626   
1                       XGboost  mod7   0.999966  0.939155  0.060810   
2                       XGboost  mod7   0.999983  0.902708  0.097275   
0  Gradient Boosting Classifier  mod8   0.992046  0.941453  0.050594   
1  Gradient Boosting Classifier  mod8   0.990745  0.930912  0.059833   
2  Gradient Boosting Classifier  mod8   0.995448  0.924653  0.070795   

   F1_W-train  F1_W-test  F1_W_diff  
0    0.933641   0.921072   0.012568  
1    0.916424   0.915811   0.000614  
2    0.956707   0.912235   0.044473  
0    0.880163   0.861686   0.018477  
1    0.876537   0.879949   0.003412  
2    0.881399   0.870719   0.010680  
0    0.876395   0.874869   0.001526  
1    0.879179   0.874869   0.004310  
2    0.888208   0.876779   0.011429  
0    0.998858   0.914010   0.084848  
1    0.997723   0.907310   0.090413  
2    0.997725   0.889651   0.108075  
0    0.991852   0.895016   0.096836  
1    0.989454   0.912014   0.077439  
2    0.991809   0.908176   0.083633  
0    0.942991   0.921505   0.021487  
1    0.939485   0.933225   0.006260  
2    0.955798   0.896050   0.059748  
0    0.996553   0.918860   0.077693  
1    0.997695   0.928620   0.069074  
2    0.998852   0.909548   0.089304  
0    0.978215   0.917042   0.061172  
1    0.977260   0.933225   0.044035  
2    0.979691   0.903075   0.076616

In [409]:
res.sort_values(by='AUC-test',ascending=False)

Name Model  AUC-train  AUC-test  AUC_diff  \
0                      ADAboost  mod6   0.970308  0.955068  0.015241   
1                      ADAboost  mod6   0.972808  0.952432  0.020376   
0           Logistic Regression  mod1   0.963399  0.949595  0.013804   
0  Gradient Boosting Classifier  mod8   0.992046  0.941453  0.050594   
1           Logistic Regression  mod1   0.939812  0.941385  0.001573   
1                       XGboost  mod7   0.999966  0.939155  0.060810   
0                       XGboost  mod7   0.999923  0.937297  0.062626   
0      Random Forest Classifier  mod5   0.999829  0.932128  0.067700   
1  Gradient Boosting Classifier  mod8   0.990745  0.930912  0.059833   
1                  ComplementNB  mod2   0.922530  0.925318  0.002788   
0                  ComplementNB  mod2   0.923848  0.924788  0.000939   
2  Gradient Boosting Classifier  mod8   0.995448  0.924653  0.070795   
2           Logistic Regression  mod1   0.979561  0.913056  0.066505   
2                  ComplementNB  mod2   0.929258  0.906727  0.022530   
1      Random Forest Classifier  mod5   0.999675  0.904493  0.095181   
2                       XGboost  mod7   0.999983  0.902708  0.097275   
2      Random Forest Classifier  mod5   0.999814  0.855625  0.144189   
2                      ADAboost  mod6   0.984215  0.855208  0.129006   
0                           SVC  mod3   0.993296  0.765068  0.228229   
2                           SVC  mod3   0.991858  0.749861  0.241997   
1      Decision Tree Classifier  mod4   0.999966  0.693007  0.306959   
1                           SVC  mod3   0.997568  0.684831  0.312737   
0      Decision Tree Classifier  mod4   0.999991  0.652568  0.347424   
2      Decision Tree Classifier  mod4   0.999983  0.648056  0.351928   

   F1_W-train  F1_W-test  F1_W_diff  
0    0.942991   0.921505   0.021487  
1    0.939485   0.933225   0.006260  
0    0.933641   0.921072   0.012568  
0    0.978215   0.917042   0.061172  
1    0.916424   0.915811   0.000614  
1    0.997695   0.928620   0.069074  
0    0.996553   0.918860   0.077693  
0    0.991852   0.895016   0.096836  
1    0.977260   0.933225   0.044035  
1    0.876537   0.879949   0.003412  
0    0.880163   0.861686   0.018477  
2    0.979691   0.903075   0.076616  
2    0.956707   0.912235   0.044473  
2    0.881399   0.870719   0.010680  
1    0.989454   0.912014   0.077439  
2    0.998852   0.909548   0.089304  
2    0.991809   0.908176   0.083633  
2    0.955798   0.896050   0.059748  
0    0.876395   0.874869   0.001526  
2    0.888208   0.876779   0.011429  
1    0.997723   0.907310   0.090413  
1    0.879179   0.874869   0.004310  
0    0.998858   0.914010   0.084848  
2    0.997725   0.889651   0.108075

In [410]:
res.sort_values(by='F1_W-test',ascending=False)

Name Model  AUC-train  AUC-test  AUC_diff  \
1  Gradient Boosting Classifier  mod8   0.990745  0.930912  0.059833   
1                      ADAboost  mod6   0.972808  0.952432  0.020376   
1                       XGboost  mod7   0.999966  0.939155  0.060810   
0                      ADAboost  mod6   0.970308  0.955068  0.015241   
0           Logistic Regression  mod1   0.963399  0.949595  0.013804   
0                       XGboost  mod7   0.999923  0.937297  0.062626   
0  Gradient Boosting Classifier  mod8   0.992046  0.941453  0.050594   
1           Logistic Regression  mod1   0.939812  0.941385  0.001573   
0      Decision Tree Classifier  mod4   0.999991  0.652568  0.347424   
2           Logistic Regression  mod1   0.979561  0.913056  0.066505   
1      Random Forest Classifier  mod5   0.999675  0.904493  0.095181   
2                       XGboost  mod7   0.999983  0.902708  0.097275   
2      Random Forest Classifier  mod5   0.999814  0.855625  0.144189   
1      Decision Tree Classifier  mod4   0.999966  0.693007  0.306959   
2  Gradient Boosting Classifier  mod8   0.995448  0.924653  0.070795   
2                      ADAboost  mod6   0.984215  0.855208  0.129006   
0      Random Forest Classifier  mod5   0.999829  0.932128  0.067700   
2      Decision Tree Classifier  mod4   0.999983  0.648056  0.351928   
1                  ComplementNB  mod2   0.922530  0.925318  0.002788   
2                           SVC  mod3   0.991858  0.749861  0.241997   
1                           SVC  mod3   0.997568  0.684831  0.312737   
0                           SVC  mod3   0.993296  0.765068  0.228229   
2                  ComplementNB  mod2   0.929258  0.906727  0.022530   
0                  ComplementNB  mod2   0.923848  0.924788  0.000939   

   F1_W-train  F1_W-test  F1_W_diff  
1    0.977260   0.933225   0.044035  
1    0.939485   0.933225   0.006260  
1    0.997695   0.928620   0.069074  
0    0.942991   0.921505   0.021487  
0    0.933641   0.921072   0.012568  
0    0.996553   0.918860   0.077693  
0    0.978215   0.917042   0.061172  
1    0.916424   0.915811   0.000614  
0    0.998858   0.914010   0.084848  
2    0.956707   0.912235   0.044473  
1    0.989454   0.912014   0.077439  
2    0.998852   0.909548   0.089304  
2    0.991809   0.908176   0.083633  
1    0.997723   0.907310   0.090413  
2    0.979691   0.903075   0.076616  
2    0.955798   0.896050   0.059748  
0    0.991852   0.895016   0.096836  
2    0.997725   0.889651   0.108075  
1    0.876537   0.879949   0.003412  
2    0.888208   0.876779   0.011429  
1    0.879179   0.874869   0.004310  
0    0.876395   0.874869   0.001526  
2    0.881399   0.870719   0.010680  
0    0.880163   0.861686   0.018477

AUC-test score shows that the best model by both score and diffrance between train score to test score is <b> ADAboost </b>