# Activisim Prediction

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
from sklearn import metrics
from pandas.api.types import CategoricalDtype
import pyMechkar as pyMechkar
from pyMechkar import analysis

In [2]:
# Train df
df = pd.read_csv("c:/Users/Mayer/Documents/DataScience/She Code/Global Activism/SC_FinalFiles/ActivismTrain.csv")
dftest = pd.read_csv("c:/Users/Mayer/Documents/DataScience/She Code/Global Activism/SC_FinalFiles/ActivismTest.csv")

In [3]:
df.head()

Succession  ActivistHQ_1  ActivistHQ_2  ActivistHQ_3  ActivistHQ_4  \
0           1             0             1             0             0   
1           1             0             1             0             0   
2           1             0             0             0             0   
3           1             0             1             0             0   
4           1             0             1             0             0   

   ActivistHQ_5  ActivistHQ_6  ActivistHQ_10  ActivistHQ_11  ActivistHQ_12  \
0             0             0              0              0              0   
1             0             0              0              0              0   
2             1             0              0              0              0   
3             0             0              0              0              0   
4             0             0              0              0              0   

   ...  Unsuccessful_1  Unsuccessful_2  CompromiseOrSettlement_1  \
0  ...               0               1                         1   
1  ...               1               0                         1   
2  ...               0               1                         1   
3  ...               0               1                         1   
4  ...               0               1                         1   

   CompromiseOrSettlement_2  Unresolved_1  Unresolved_2  hclust3  hclust4  \
0                         0             1             0        1        1   
1                         0             1             0        2        2   
2                         0             1             0        2        2   
3                         0             1             0        1        1   
4                         0             1             0        1        1   

   Mclust3  Mclust4  
0        3        3  
1        1        1  
2        1        1  
3        3        3  
4        3        3  

[5 rows x 2951 columns]

In [4]:
df.select_dtypes("object")


Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[5579 rows x 0 columns]

In [5]:
df.describe()

Succession  ActivistHQ_1  ActivistHQ_2  ActivistHQ_3  ActivistHQ_4  \
count  5579.000000   5579.000000   5579.000000   5579.000000   5579.000000   
mean      0.751031      0.061839      0.697437      0.028679      0.009321   
std       0.432455      0.240885      0.459409      0.166918      0.096101   
min       0.000000      0.000000      0.000000      0.000000      0.000000   
25%       1.000000      0.000000      0.000000      0.000000      0.000000   
50%       1.000000      0.000000      1.000000      0.000000      0.000000   
75%       1.000000      0.000000      1.000000      0.000000      0.000000   
max       1.000000      1.000000      1.000000      1.000000      1.000000   

       ActivistHQ_5  ActivistHQ_6  ActivistHQ_10  ActivistHQ_11  \
count   5579.000000   5579.000000    5579.000000    5579.000000   
mean       0.055386      0.007707       0.010396       0.029754   
std        0.228753      0.087461       0.101439       0.169924   
min        0.000000      0.000000       0.000000       0.000000   
25%        0.000000      0.000000       0.000000       0.000000   
50%        0.000000      0.000000       0.000000       0.000000   
75%        0.000000      0.000000       0.000000       0.000000   
max        1.000000      1.000000       1.000000       1.000000   

       ActivistHQ_12  ...  Unsuccessful_1  Unsuccessful_2  \
count    5579.000000  ...     5579.000000     5579.000000   
mean        0.000896  ...        0.247177        0.752823   
std         0.029926  ...        0.431409        0.431409   
min         0.000000  ...        0.000000        0.000000   
25%         0.000000  ...        0.000000        1.000000   
50%         0.000000  ...        0.000000        1.000000   
75%         0.000000  ...        0.000000        1.000000   
max         1.000000  ...        1.000000        1.000000   

       CompromiseOrSettlement_1  CompromiseOrSettlement_2  Unresolved_1  \
count               5579.000000               5579.000000   5579.000000   
mean                   0.984585                  0.015415      0.971859   
std                    0.123207                  0.123207      0.165391   
min                    0.000000                  0.000000      0.000000   
25%                    1.000000                  0.000000      1.000000   
50%                    1.000000                  0.000000      1.000000   
75%                    1.000000                  0.000000      1.000000   
max                    1.000000                  1.000000      1.000000   

       Unresolved_2      hclust3      hclust4      Mclust3      Mclust4  
count   5579.000000  5579.000000  5579.000000  5579.000000  5579.000000  
mean       0.028141     1.508156     1.680767     2.281233     2.705682  
std        0.165391     0.745295     1.083337     0.852700     0.932725  
min        0.000000     1.000000     1.000000     1.000000     1.000000  
25%        0.000000     1.000000     1.000000     1.000000     2.000000  
50%        0.000000     1.000000     1.000000     3.000000     3.000000  
75%        0.000000     2.000000     2.000000     3.000000     3.000000  
max        1.000000     3.000000     4.000000     3.000000     4.000000  

[8 rows x 2951 columns]

In [6]:
dftest.describe()

Succession  ActivistHQ_1  ActivistHQ_2  ActivistHQ_3  ActivistHQ_4  \
count  3720.000000   3720.000000   3720.000000   3720.000000   3720.000000   
mean      0.749731      0.066935      0.696774      0.030376      0.007796   
std       0.433226      0.249944      0.459714      0.171644      0.087960   
min       0.000000      0.000000      0.000000      0.000000      0.000000   
25%       0.000000      0.000000      0.000000      0.000000      0.000000   
50%       1.000000      0.000000      1.000000      0.000000      0.000000   
75%       1.000000      0.000000      1.000000      0.000000      0.000000   
max       1.000000      1.000000      1.000000      1.000000      1.000000   

       ActivistHQ_5  ActivistHQ_6  ActivistHQ_10  ActivistHQ_11  \
count   3720.000000   3720.000000    3720.000000    3720.000000   
mean       0.055108      0.010215       0.006452       0.031452   
std        0.228221      0.100566       0.080073       0.174558   
min        0.000000      0.000000       0.000000       0.000000   
25%        0.000000      0.000000       0.000000       0.000000   
50%        0.000000      0.000000       0.000000       0.000000   
75%        0.000000      0.000000       0.000000       0.000000   
max        1.000000      1.000000       1.000000       1.000000   

       ActivistHQ_12  ...  Unsuccessful_1  Unsuccessful_2  \
count    3720.000000  ...     3720.000000     3720.000000   
mean        0.000806  ...        0.232527        0.767473   
std         0.028390  ...        0.422500        0.422500   
min         0.000000  ...        0.000000        0.000000   
25%         0.000000  ...        0.000000        1.000000   
50%         0.000000  ...        0.000000        1.000000   
75%         0.000000  ...        0.000000        1.000000   
max         1.000000  ...        1.000000        1.000000   

       CompromiseOrSettlement_1  CompromiseOrSettlement_2  Unresolved_1  \
count               3720.000000               3720.000000   3720.000000   
mean                   0.986828                  0.013172      0.972849   
std                    0.114026                  0.114026      0.162544   
min                    0.000000                  0.000000      0.000000   
25%                    1.000000                  0.000000      1.000000   
50%                    1.000000                  0.000000      1.000000   
75%                    1.000000                  0.000000      1.000000   
max                    1.000000                  1.000000      1.000000   

       Unresolved_2    hclust3      hclust4      Mclust3      Mclust4  
count   3720.000000  3720.0000  3720.000000  3720.000000  3720.000000  
mean       0.027151     1.5500     1.748118     2.240591     2.678763  
std        0.162544     0.7689     1.127880     0.866401     0.943001  
min        0.000000     1.0000     1.000000     1.000000     1.000000  
25%        0.000000     1.0000     1.000000     1.000000     2.000000  
50%        0.000000     1.0000     1.000000     3.000000     3.000000  
75%        0.000000     2.0000     2.000000     3.000000     3.000000  
max        1.000000     3.0000     4.000000     3.000000     4.000000  

[8 rows x 2951 columns]

In [7]:
df2 = df.copy()
df2.dtypes[df.columns[0:1]]
df2['Succession'] = df2['Succession'].astype('category')

In [8]:
dftest2 = dftest.copy()
dftest2.dtypes[df.columns[0:1]]
dftest2['Succession'] = dftest2['Succession'].astype('category')

In [9]:
df2.iloc[:,1:2948]


ActivistHQ_1  ActivistHQ_2  ActivistHQ_3  ActivistHQ_4  ActivistHQ_5  \
0                0             1             0             0             0   
1                0             1             0             0             0   
2                0             0             0             0             1   
3                0             1             0             0             0   
4                0             1             0             0             0   
...            ...           ...           ...           ...           ...   
5574             0             1             0             0             0   
5575             0             1             0             0             0   
5576             0             1             0             0             0   
5577             0             1             0             0             0   
5578             0             0             0             0             0   

      ActivistHQ_6  ActivistHQ_10  ActivistHQ_11  ActivistHQ_12  \
0                0              0              0              0   
1                0              0              0              0   
2                0              0              0              0   
3                0              0              0              0   
4                0              0              0              0   
...            ...            ...            ...            ...   
5574             0              0              0              0   
5575             0              0              0              0   
5576             0              0              0              0   
5577             0              0              0              0   
5578             0              0              0              0   

      ActivistHQ_13  ...  PartiallySuccessful_2  Successful_1  Successful_2  \
0                 0  ...                      0             1             0   
1                 0  ...                      0             1             0   
2                 0  ...                      0             0             1   
3                 0  ...                      1             0             1   
4                 0  ...                      1             1             0   
...             ...  ...                    ...           ...           ...   
5574              0  ...                      0             0             1   
5575              0  ...                      0             1             0   
5576              0  ...                      0             1             0   
5577              0  ...                      0             1             0   
5578              0  ...                      0             1             0   

      Unsuccessful_1  Unsuccessful_2  CompromiseOrSettlement_1  \
0                  0               1                         1   
1                  1               0                         1   
2                  0               1                         1   
3                  0               1                         1   
4                  0               1                         1   
...              ...             ...                       ...   
5574               0               1                         1   
5575               0               1                         1   
5576               1               0                         1   
5577               0               1                         1   
5578               0               1                         1   

      CompromiseOrSettlement_2  Unresolved_1  Unresolved_2  hclust3  
0                            0             1             0        1  
1                            0             1             0        2  
2                            0             1             0        2  
3                            0             1             0        1  
4                            0             1             0        1  
...                        ...           ...           ...      ...  
5574                         0  

In [10]:
X_train = df2.iloc[:,1:2947]
nc_ = df2.iloc[:,2948:2951] #clusters
y_train = df2.Succession

In [11]:
X_test = df2.iloc[:,1:2947]
y_test = df2.Succession

In [12]:
X_train.head()

ActivistHQ_1  ActivistHQ_2  ActivistHQ_3  ActivistHQ_4  ActivistHQ_5  \
0             0             1             0             0             0   
1             0             1             0             0             0   
2             0             0             0             0             1   
3             0             1             0             0             0   
4             0             1             0             0             0   

   ActivistHQ_6  ActivistHQ_10  ActivistHQ_11  ActivistHQ_12  ActivistHQ_13  \
0             0              0              0              0              0   
1             0              0              0              0              0   
2             0              0              0              0              0   
3             0              0              0              0              0   
4             0              0              0              0              0   

   ...  PartiallySuccessful_1  PartiallySuccessful_2  Successful_1  \
0  ...                      1                      0             1   
1  ...                      1                      0             1   
2  ...                      1                      0             0   
3  ...                      0                      1             0   
4  ...                      0                      1             1   

   Successful_2  Unsuccessful_1  Unsuccessful_2  CompromiseOrSettlement_1  \
0             0               0               1                         1   
1             0               1               0                         1   
2             1               0               1                         1   
3             1               0               1                         1   
4             0               0               1                         1   

   CompromiseOrSettlement_2  Unresolved_1  Unresolved_2  
0                         0             1             0  
1                         0             1             0  
2                         0             1             0  
3                         0             1             0  
4                         0             1             0  

[5 rows x 2946 columns]

In [13]:
y_train.head()

0    1
1    1
2    1
3    1
4    1
Name: Succession, dtype: category
Categories (2, int64): [0, 1]

# Metric Selection

In [93]:
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve

### Logistic Regression

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
mod1 = LogisticRegression()
mod1.fit(X_train,y_train)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
yhat1 = mod1.predict(X_train)
yhat1

array([0, 1, 1, ..., 1, 0, 1], dtype=int64)

In [18]:
yprob1 = mod1.predict_proba(X_train)
yprob1

array([[0.51114389, 0.48885611],
       [0.28747168, 0.71252832],
       [0.01702669, 0.98297331],
       ...,
       [0.01005296, 0.98994704],
       [0.98230077, 0.01769923],
       [0.03315122, 0.96684878]])

In [19]:
pd.crosstab(y_train,yhat1)

C:\Users\Mayer\Anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:277: FutureWarning: Categorical.ravel will return a Categorical object instead of an ndarray in a future version.
  vec = libmissing.isnaobj_old(values.ravel())


col_0         0     1
Succession           
0           808   581
1           249  3941

In [20]:
### AUC - without CV:
print('AUC= %f' % roc_auc_score(y_train,yhat1))

# metrics with CV
scoring = {'ROC_AUC': 'roc_auc',
           'F1': make_scorer(f1_score, average='binary'),
           'F1_weighted': make_scorer(f1_score, average='weighted')}
scores = cross_validate(mod1, X_train, y_train, scoring=scoring,
                        cv=4, return_train_score=True)
sorted(scores.keys())

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


AUC= 0.761143


C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


['fit_time',
 'score_time',
 'test_F1',
 'test_F1_weighted',
 'test_ROC_AUC',
 'train_F1',
 'train_F1_weighted',
 'train_ROC_AUC']

In [21]:
sklearn.metrics.SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'accuracy', 'roc_auc', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'brier_score_loss', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

In [22]:
yhat2 = mod1.predict(X_test)

In [23]:
scores_test = cross_validate(mod1, X_test, y_test, scoring=scoring,
                        cv=4, return_train_score=True)
sorted(scores_test.keys())


C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


['fit_time',
 'score_time',
 'test_F1',
 'test_F1_weighted',
 'test_ROC_AUC',
 'train_F1',
 'train_F1_weighted',
 'train_ROC_AUC']

In [24]:
### AUC
print(scores['train_ROC_AUC'])
print(scores_test['train_ROC_AUC'])

[0.91734264 0.91949973 0.91741221 0.91725801]
[0.91734264 0.91949973 0.91741221 0.91725801]


In [25]:
### F1 Score
print(scores['train_F1'])
print(scores_test['train_F1'])

[0.90596717 0.90900721 0.91061879 0.90645506]
[0.90596717 0.90900721 0.91061879 0.90645506]


In [26]:
### F1_weighted Score
print(scores['train_F1_weighted'])
print(scores_test['train_F1_weighted'])

[0.84677309 0.85188285 0.85306187 0.84574658]
[0.84677309 0.85188285 0.85306187 0.84574658]


We can clearly see that <b> roc_auc </b>and<b> f1 </b>(taking imbalance into account) are better then f1-weight

The false positive rate is FPR= fp/[fp+tn]
<br>False Positive Rate = 1 - Specificity</br>

In [111]:
scoring = {'ROC_AUC': 'roc_auc',
           'F1': make_scorer(f1_score),
           'sensitivity': make_scorer(recall_score),
           'specificity': make_scorer(recall_score,pos_label=0)
          }

## CV strategy Selection

Some classification problems can exhibit a large imbalance in the distribution of the target classes: for instance there could be several times more negative samples than positive samples. In such cases it is recommended to use stratified sampling as implemented in StratifiedKFold and StratifiedShuffleSplit to ensure that relative class frequencies is approximately preserved in each train and validation fold.

In [28]:
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.model_selection import StratifiedShuffleSplit

In [29]:
skf = StratifiedKFold(n_splits=3, shuffle=False, random_state=952)

skf.split(X_train, y_train)


<generator object _BaseKFold.split at 0x00000187C4F9E8B8>

In [30]:
sss = StratifiedShuffleSplit(n_splits=3, test_size=0.5, random_state=952)
sss.split(X_train, y_train)

<generator object BaseShuffleSplit.split at 0x00000187C4F9EB10>

In [31]:
from  sklearn.linear_model import LogisticRegressionCV

In [32]:
mod1 = LogisticRegressionCV(cv=skf,solver='liblinear',random_state=952).fit(X_train,y_train)
mod2 = LogisticRegressionCV(cv=sss,solver='liblinear',random_state=952).fit(X_train,y_train)

In [33]:
scores_skf = cross_validate(mod1, X_train, y_train, scoring=scoring, return_train_score=True)
scores_sss = cross_validate(mod2, X_train, y_train, scoring=scoring, return_train_score=True)
print('ROC_AUC')
print(scores_skf['train_ROC_AUC'])
print(scores_sss['train_ROC_AUC'])

print('F1')
print(scores_skf['train_F1'])
print(scores_sss['train_F1'])

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


ROC_AUC
[0.89822153 0.89721314 0.89706035]
[0.89822153 0.89721314 0.89706035]
F1
[0.89874936 0.89653991 0.89906063]
[0.89874936 0.89653991 0.89906063]


I will use <b>StratifiedShuffleSplit</b> as Corss validation startegy

# Cross  Validation Models

### LogisticReggressionCV

In [34]:
#mod1 = LogisticRegressionCV(cv=sss,solver='liblinear',random_state=383).fit(X_train,y_train)
mod1 = LogisticRegressionCV(random_state=383).fit(X_train,y_train)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the n

In [112]:
scores_lr = cross_validate(mod1, X_train, y_train, scoring=scoring, return_train_score=True)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the n

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the n

In [36]:
#res = {'Logistic Regression':{
#           'AUC-train':scores_lr['train_ROC_AUC'],
#           'AUC-test':scores_lr['test_ROC_AUC'],
#           'F1_W-train':scores_lr['train_F1_weighted'],
#           'F1_W-test' : scores_lr['test_F1_weighted']
#          
#      }}

In [128]:
res = {'Name':'Logistic Regression',
        'Model':'mod1',
        'AUC-train':scores_lr['train_ROC_AUC'],
        'AUC-test':scores_lr['test_ROC_AUC'],
        'F1-train':scores_lr['train_F1'],
        'F1-test' : scores_lr['test_F1'],
        'Sensitivity-train': scores_lr['train_sensitivity'],
        'Sensitivity-test': scores_lr['test_sensitivity'],
        'fpr-train': 1-scores_lr['train_specificity'],
        'fpr-test': 1-scores_lr['test_specificity']
          
      }
res = pd.DataFrame(res)

In [121]:
res

Name Model  AUC-train  AUC-test  F1-train   F1-test  \
0  Logistic Regression  mod1   0.898274  0.841868  0.899092  0.873326   
1  Logistic Regression  mod1   0.897233  0.844349  0.896694  0.877349   
2  Logistic Regression  mod1   0.897094  0.848336  0.898873  0.874362   

   Sensitivity-train  Sensitivity-test  fpr-train  fpr-test  
0           0.939492          0.910523   0.453564  0.526998  
1           0.936985          0.919112   0.461123  0.531317  
2           0.941661          0.919771   0.463283  0.555076

### ComplementNB 

It is particularly suited for imbalanced data sets.

In [38]:
#from sklearn.linear_model import ElasticNetCV
from sklearn.naive_bayes import ComplementNB

In [39]:
mod2 = ComplementNB().fit(X_train,y_train)

In [59]:
scores_CNB = cross_validate(mod2, X_train, y_train, scoring=scoring, return_train_score=True)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [41]:
#res ['ComplementNB'] = {
#           'AUC-train':scores_CNB['train_ROC_AUC'],
#           'AUC-test':scores_CNB['test_ROC_AUC'],
#           'F1_W-train':scores_CNB['train_F1_weighted'],
#           'F1_W-test' : scores_CNB['test_F1_weighted']
#          
#      }

In [129]:
res2 = {'Name':'ComplementNB',
        'Model':'mod2',
        'AUC-train':scores_CNB['train_ROC_AUC'],
        'AUC-test':scores_CNB['test_ROC_AUC'],
        'F1-train':scores_CNB['train_F1'],
        'F1-test' : scores_CNB['test_F1'],
        'Sensitivity-train': scores_CNB['train_sensitivity'],
        'Sensitivity-test': scores_CNB['test_sensitivity'],
        'fpr-train': 1-scores_CNB['train_specificity'],
        'fpr-test': 1-scores_CNB['test_specificity']
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

### Support Vector Machine Classifaier (SVC)

In [43]:
from sklearn.svm import SVC

In [44]:
#mod3 = SVC(gamma = 'scale',kernel = 'sigmoid', class_weight = 'balanced',random_state=383).fit(X_train,y_train)
mod3 = SVC(random_state=383).fit(X_train,y_train)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [61]:
scores_SVC = cross_validate(mod3, X_train, y_train,  scoring=scoring, return_train_score=True)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto'

In [130]:
res2 = {'Name':'SVC',
        'Model':'mod3',
        'AUC-train':scores_SVC['train_ROC_AUC'],
        'AUC-test':scores_SVC['test_ROC_AUC'],
        'F1-train':scores_SVC['train_F1'],
        'F1-test' : scores_SVC['test_F1'],
        'Sensitivity-train': scores_SVC['train_sensitivity'],
        'Sensitivity-test': scores_SVC['test_sensitivity'],
        'fpr-train': 1-scores_SVC['train_specificity'],
        'fpr-test': 1-scores_SVC['test_specificity']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

### Classification Trees

In [47]:
from sklearn.tree import DecisionTreeClassifier

#mod4 = DecisionTreeClassifier(random_state=383, class_weight = 'balanced').fit(X_train,y_train)
mod4 = DecisionTreeClassifier(random_state=383).fit(X_train,y_train)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [64]:
scores_DTC = cross_validate(mod4, X_train, y_train, scoring=scoring, return_train_score=True)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [131]:
res2 = {'Name':'Decision Tree Classifier',
        'Model':'mod4',
        'AUC-train':scores_DTC['train_ROC_AUC'],
        'AUC-test':scores_DTC['test_ROC_AUC'],
        'F1-train':scores_DTC['train_F1'],
        'F1-test' : scores_DTC['test_F1'],
        'Sensitivity-train': scores_DTC['train_sensitivity'],
        'Sensitivity-test': scores_DTC['test_sensitivity'],
        'fpr-train': 1-scores_DTC['train_specificity'],
        'fpr-test': 1-scores_DTC['test_specificity']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

### Random Forest

In [48]:
from sklearn.ensemble import RandomForestClassifier

#mod5 = RandomForestClassifier(random_state=383, class_weight = 'balanced').fit(X_train,y_train)
mod5 = RandomForestClassifier(random_state=383).fit(X_train,y_train)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [74]:
scores_rf = cross_validate(mod5, X_train, y_train, scoring=scoring, return_train_score=True)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [132]:
res2 = {'Name':'Random Forest Classifier',
        'Model':'mod5',
        'AUC-train':scores_rf['train_ROC_AUC'],
        'AUC-test':scores_rf['test_ROC_AUC'],
        'F1-train':scores_rf['train_F1'],
        'F1-test' : scores_rf['test_F1'],
        'Sensitivity-train': scores_rf['train_sensitivity'],
        'Sensitivity-test': scores_rf['test_sensitivity'],
        'fpr-train': 1-scores_rf['train_specificity'],
        'fpr-test': 1-scores_rf['test_specificity']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

### ADAboost

In [49]:
from sklearn.ensemble import AdaBoostClassifier

mod6 = AdaBoostClassifier(random_state=383).fit(X_train,y_train)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [76]:
scores_ADA = cross_validate(mod6, X_train, y_train, scoring=scoring, return_train_score=True)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [133]:
res2 = {'Name':'ADAboost',
        'Model':'mod6',
        'AUC-train':scores_ADA['train_ROC_AUC'],
        'AUC-test':scores_ADA['test_ROC_AUC'],
        'F1-train':scores_ADA['train_F1'],
        'F1-test' : scores_ADA['test_F1'],
        'Sensitivity-train': scores_ADA['train_sensitivity'],
        'Sensitivity-test': scores_ADA['test_sensitivity'],
        'fpr-train': 1-scores_ADA['train_specificity'],
        'fpr-test': 1-scores_ADA['test_specificity']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

### eXtreme Gradient Boosting (XGboost)

In [50]:
from xgboost import XGBClassifier
from xgboost import cv
from xgboost import DMatrix

weights = {0: 1, 1: 3}
#dtrain = DMatrix(np.array(X_train), label=y_train,weight = weights)
#params = {'max_depth':3, 'eta':1, 'objective':"reg:logistic"}

#mod7 = XGBClassifier(objective='reg:logistic',random_state=383)
mod7 = XGBClassifier(random_state=383)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [78]:
scores_XGB = cross_validate(mod7, X_train, y_train, scoring=scoring, return_train_score=True)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [134]:
res2 = {'Name':'XGboost',
        'Model':'mod7',
        'AUC-train':scores_XGB['train_ROC_AUC'],
        'AUC-test':scores_XGB['test_ROC_AUC'],
        'F1-train':scores_XGB['train_F1'],
        'F1-test' : scores_XGB['test_F1'],
        'Sensitivity-train': scores_XGB['train_sensitivity'],
        'Sensitivity-test': scores_XGB['test_sensitivity'],
        'fpr-train': 1-scores_XGB['train_specificity'],
        'fpr-test': 1-scores_XGB['test_specificity']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

### GradientBoostingClassifier

In [51]:
from sklearn.ensemble import GradientBoostingClassifier

mod8 = GradientBoostingClassifier(random_state=383).fit(X_train,y_train)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [80]:
scores_GBC = cross_validate(mod8, X_train, y_train, scoring=scoring, return_train_score=True)

C:\Users\Mayer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [135]:
res2 = {'Name':'Gradient Boosting Classifier',
        'Model':'mod8',
        'AUC-train':scores_GBC['train_ROC_AUC'],
        'AUC-test':scores_GBC['test_ROC_AUC'],
        'F1-train':scores_GBC['train_F1'],
        'F1-test' : scores_GBC['test_F1'],
        'Sensitivity-train': scores_GBC['train_sensitivity'],
        'Sensitivity-test': scores_GBC['test_sensitivity'],
        'fpr-train': 1-scores_GBC['train_specificity'],
        'fpr-test': 1-scores_GBC['test_specificity']
          
      }
res2 = pd.DataFrame(res2)
res = pd.concat([res, res2])

## Results

In [136]:
res.insert(4,'AUC_diff',abs(res['AUC-train']-res['AUC-test']))
res.insert(7,'F1_diff',abs(res['F1-train']-res['F1-test']))
res.insert(10,'sens_diff',abs(res['Sensitivity-train']-res['Sensitivity-test']))
res.insert(13,'fpr_diff',abs(res['fpr-train']-res['fpr-test']))
res

Name Model  AUC-train  AUC-test  AUC_diff  \
0           Logistic Regression  mod1   0.898274  0.841868  0.056406   
1           Logistic Regression  mod1   0.897233  0.844349  0.052885   
2           Logistic Regression  mod1   0.897094  0.848336  0.048758   
0                  ComplementNB  mod2   0.761277  0.695748  0.065529   
1                  ComplementNB  mod2   0.757936  0.681560  0.076376   
2                  ComplementNB  mod2   0.759515  0.717470  0.042045   
0                           SVC  mod3   0.841789  0.812042  0.029747   
1                           SVC  mod3   0.845187  0.824536  0.020651   
2                           SVC  mod3   0.847208  0.818621  0.028588   
0      Decision Tree Classifier  mod4   0.999984  0.678691  0.321294   
1      Decision Tree Classifier  mod4   0.999993  0.662455  0.337537   
2      Decision Tree Classifier  mod4   0.999988  0.693839  0.306149   
0      Random Forest Classifier  mod5   0.999175  0.773250  0.225925   
1      Random Forest Classifier  mod5   0.999260  0.752747  0.246513   
2      Random Forest Classifier  mod5   0.999095  0.760225  0.238869   
0                      ADAboost  mod6   0.870145  0.826714  0.043431   
1                      ADAboost  mod6   0.871375  0.841471  0.029905   
2                      ADAboost  mod6   0.871031  0.836379  0.034652   
0                       XGboost  mod7   0.985828  0.833010  0.152818   
1                       XGboost  mod7   0.981824  0.833186  0.148637   
2                       XGboost  mod7   0.982256  0.834246  0.148009   
0  Gradient Boosting Classifier  mod8   0.898423  0.846752  0.051671   
1  Gradient Boosting Classifier  mod8   0.897174  0.849202  0.047971   
2  Gradient Boosting Classifier  mod8   0.895010  0.851578  0.043432   

   F1-train   F1-test   F1_diff  Sensitivity-train  Sensitivity-test  \
0  0.899092  0.873326  0.025766           0.939492          0.910523   
1  0.896694  0.877349  0.019345           0.936985          0.919112   
2  0.898873  0.874362  0.024511           0.941661          0.919771   
0  0.796791  0.765163  0.031628           0.746867          0.704366   
1  0.789504  0.760886  0.028618           0.732546          0.712956   
2  0.794563  0.766847  0.027715           0.742663          0.709169   
0  0.857801  0.857845  0.000044           1.000000          1.000000   
1  0.857801  0.857845  0.000044           1.000000          1.000000   
2  0.857845  0.857757  0.000087           1.000000          1.000000   
0  0.998386  0.842781  0.155605           0.996778          0.846099   
1  0.998925  0.832200  0.166725           0.998210          0.832498   
2  0.998566  0.853901  0.144666           0.997137          0.862464   
0  0.992123  0.849551  0.142572           0.992123          0.881174   
1  0.993022  0.849437  0.143585           0.993555          0.890480   
2  0.992342  0.852991  0.139351           0.997137          0.904011   
0  0.880318  0.864436  0.015882           0.911207          0.896922   
1  0.879447  0.867238  0.012209           0.911565          0.904796   
2  0.879227  0.866136  0.013091           0.911954          0.896848   
0  0.963237  0.868330  0.094907           0.980308          0.896922   
1  0.956293  0.864902  0.091391           0.975295          0.900501   
2  0.960434  0.856745  0.103690           0.981747          0.880372   
0  0.891411  0.869654  0.021757           0.941998          0.916965   
1  0.894374  0.879195  0.015180           0.953455          0.937724   
2  0.891282  0.876722  0.014561           0.947745          0.934814   

   sens_diff  fpr-train  fpr-test  fpr_diff  
0   0.028969   0.453564  0.526998  0.073434  
1   0.017873   0.461123  0.531317  0.070194  
2   0.021890   0.463283  0.555076  0.091793  
0   0.042501   0.385529  0.412527  0.026998  
1   0.019589   0.371490  0.485961  0.114471  
2   0.033494   0.382289  0.423326  0.041037  
0   0.000000   1.000000  1.000000  0.000000  
1   0.000000   1.000000  1.000000  0.000000  
2   0.00000

In [137]:
res.sort_values(by='Sensitivity-test',ascending=False)

Name Model  AUC-train  AUC-test  AUC_diff  \
2                           SVC  mod3   0.847208  0.818621  0.028588   
0                           SVC  mod3   0.841789  0.812042  0.029747   
1                           SVC  mod3   0.845187  0.824536  0.020651   
1  Gradient Boosting Classifier  mod8   0.897174  0.849202  0.047971   
2  Gradient Boosting Classifier  mod8   0.895010  0.851578  0.043432   
2           Logistic Regression  mod1   0.897094  0.848336  0.048758   
1           Logistic Regression  mod1   0.897233  0.844349  0.052885   
0  Gradient Boosting Classifier  mod8   0.898423  0.846752  0.051671   
0           Logistic Regression  mod1   0.898274  0.841868  0.056406   
1                      ADAboost  mod6   0.871375  0.841471  0.029905   
2      Random Forest Classifier  mod5   0.999095  0.760225  0.238869   
1                       XGboost  mod7   0.981824  0.833186  0.148637   
0                      ADAboost  mod6   0.870145  0.826714  0.043431   
0                       XGboost  mod7   0.985828  0.833010  0.152818   
2                      ADAboost  mod6   0.871031  0.836379  0.034652   
1      Random Forest Classifier  mod5   0.999260  0.752747  0.246513   
0      Random Forest Classifier  mod5   0.999175  0.773250  0.225925   
2                       XGboost  mod7   0.982256  0.834246  0.148009   
2      Decision Tree Classifier  mod4   0.999988  0.693839  0.306149   
0      Decision Tree Classifier  mod4   0.999984  0.678691  0.321294   
1      Decision Tree Classifier  mod4   0.999993  0.662455  0.337537   
1                  ComplementNB  mod2   0.757936  0.681560  0.076376   
2                  ComplementNB  mod2   0.759515  0.717470  0.042045   
0                  ComplementNB  mod2   0.761277  0.695748  0.065529   

   F1-train   F1-test   F1_diff  Sensitivity-train  Sensitivity-test  \
2  0.857845  0.857757  0.000087           1.000000          1.000000   
0  0.857801  0.857845  0.000044           1.000000          1.000000   
1  0.857801  0.857845  0.000044           1.000000          1.000000   
1  0.894374  0.879195  0.015180           0.953455          0.937724   
2  0.891282  0.876722  0.014561           0.947745          0.934814   
2  0.898873  0.874362  0.024511           0.941661          0.919771   
1  0.896694  0.877349  0.019345           0.936985          0.919112   
0  0.891411  0.869654  0.021757           0.941998          0.916965   
0  0.899092  0.873326  0.025766           0.939492          0.910523   
1  0.879447  0.867238  0.012209           0.911565          0.904796   
2  0.992342  0.852991  0.139351           0.997137          0.904011   
1  0.956293  0.864902  0.091391           0.975295          0.900501   
0  0.880318  0.864436  0.015882           0.911207          0.896922   
0  0.963237  0.868330  0.094907           0.980308          0.896922   
2  0.879227  0.866136  0.013091           0.911954          0.896848   
1  0.993022  0.849437  0.143585           0.993555          0.890480   
0  0.992123  0.849551  0.142572           0.992123          0.881174   
2  0.960434  0.856745  0.103690           0.981747          0.880372   
2  0.998566  0.853901  0.144666           0.997137          0.862464   
0  0.998386  0.842781  0.155605           0.996778          0.846099   
1  0.998925  0.832200  0.166725           0.998210          0.832498   
1  0.789504  0.760886  0.028618           0.732546          0.712956   
2  0.794563  0.766847  0.027715           0.742663          0.709169   
0  0.796791  0.765163  0.031628           0.746867          0.704366   

   sens_diff  fpr-train  fpr-test  fpr_diff  
2   0.000000   1.000000  1.000000  0.000000  
0   0.000000   1.000000  1.000000  0.000000  
1   0.000000   1.000000  1.000000  0.000000  
1   0.015731   0.538877  0.589633  0.050756  
2   0.012931   0.539957  0.596112  0.056156  
2   0.021890   0.463283  0.555076  0.091793  
1   0.017873   0.461123  0.531317  0.070194  
0   0.025033   0.517279  0.578834  0.061555  
0   0.02896

We are looking for model with the highest sensitivy score (catching most of the true positive-TP) 
and the lowest fpr (false positive ratio)
<br><b> Decision Tree Classifier Classifier </b> is the best considering both parameters</br>

# Decision Tree Fine-Tuning

In [138]:
#from sklearn.metrics import mean_squared_error, mean_absolute_error
#from sklearn.metrics import score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

We will use <b> Random Search </b> for the fine tuning of the model

In [124]:
#def evaluate (model, X,y):
#    y_hat = model.predict(X)
#    AUC = roc_auc_score(y,y_hat)
#    
#    print('Model Performance')
#    print('AUC = {:0.4f}'.format(AUC))
#        
#    return [AUC]

#### Run base model

In [139]:
mod4 = DecisionTreeClassifier(random_state=383).fit(X_train,y_train)
y_hat = mod4.predict(X_train)

#mod6_AUC = evaluate (mod6, X_test,y_test)

# Return the mean accuracy on the given test data
#base_score = mod6.score(X_train, y_hat)
base_AUC = cross_validate(mod4, X_train, y_hat, scoring=make_scorer(recall_score),cv=sss, return_train_score=False)

base_res = {'Base Score':base_AUC['test_score']}
base_res = pd.DataFrame(base_res)
base_res


Base Score
0    0.847222
1    0.875000
2    0.863027

Hayperparameter Fine-Tuning

In [140]:
# The function to measure the quality of a split
criterion = ['gini', 'entropy']
# The strategy used to choose the split at each node. 
# Supported strategies are “best” to choose the best split and “random” to choose the best random split
splitter = ['best', 'random']
# The minimum number of samples required to split an internal node
min_samples_split = [2,4,8,16,32,40]
# The minimum number of samples required to be at a leaf node
min_samples_leaf = [2,4,6,8,10,12,14,16,18,20]

random_grid = {'criterion': criterion,
               'splitter': splitter,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

print(random_grid)

{'criterion': ['gini', 'entropy'], 'splitter': ['best', 'random'], 'min_samples_split': [2, 4, 8, 16, 32, 40], 'min_samples_leaf': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]}


In [141]:
DTC = DecisionTreeClassifier()

DTC_random = RandomizedSearchCV(estimator = DTC, param_distributions = random_grid, n_iter = 100, cv = sss,
                               verbose=2, random_state = 383, n_jobs=-1)

# Fit the random search model
DTC_random.fit(X_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   25.7s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  1.8min finished


RandomizedSearchCV(cv=StratifiedShuffleSplit(n_splits=3, random_state=952, test_size=0.5,
            train_size=None),
                   error_score='raise-deprecating',
                   estimator=DecisionTreeClassifier(class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features=None,
                                                    max_leaf_nodes=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_....0,
                                                    presort=False,
                                            

In [143]:
DTC_random.best_params_

{'splitter': 'best',
 'min_samples_split': 40,
 'min_samples_leaf': 18,
 'criterion': 'gini'}

In [142]:
best_random = DTC_random.best_estimator_
yhat = best_random.predict(X_train)

random_AUC = cross_validate(best_random, X_train, y_hat, scoring=make_scorer(recall_score),cv=sss, return_train_score=False)
#random_score = best_random.score(X_test, y_test)

random_res = {'Base Score':base_AUC['test_score'],
              'Random Score':random_AUC['test_score']
      }
random_res = pd.DataFrame(random_res)
random_res

Base Score  Random Score
0    0.847222      0.891762
1    0.875000      0.902778
2    0.863027      0.867816

<b>Grid Search</b> : We decide which parameters and how (not randomly)

In [144]:
# Create the parameter grid
param_grid = {'splitter': ['best'],
               'min_samples_split': [35,40,45],
               'min_samples_leaf': [17,18,19],
               'criterion': ['gini']
}

grid_search = GridSearchCV(estimator = DTC, param_grid = param_grid, cv = sss,
                           verbose=2, n_jobs=-1)

In [145]:
# Fit the grid search to the data
grid_search.fit(X_train,y_train)

Fitting 3 folds for each of 9 candidates, totalling 27 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  27 out of  27 | elapsed:   14.2s finished


GridSearchCV(cv=StratifiedShuffleSplit(n_splits=3, random_state=952, test_size=0.5,
            train_size=None),
             error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'crit

In [146]:
grid_search.best_params_

{'criterion': 'gini',
 'min_samples_leaf': 18,
 'min_samples_split': 40,
 'splitter': 'best'}

In [147]:
#the best parameters
best_grid = grid_search.best_estimator_
y_hat = best_grid.predict(X_train)

grid_AUC = cross_validate(best_grid, X_train, y_hat, scoring=make_scorer(recall_score),cv=sss, return_train_score=False)
#grid_score = best_grid.score(X_test, y_test)

grid_res = {'Base Score':base_AUC['test_score'],
            'Random Score':random_AUC['test_score'],
            'Grid Score':grid_AUC['test_score']
      }
grid_res = pd.DataFrame(grid_res)
grid_res

Base Score  Random Score  Grid Score
0    0.847222      0.891762    0.966696
1    0.875000      0.902778    0.961368
2    0.863027      0.867816    0.962256

We can see the improvment between base, random and grid fine tuning

# Predict the final results

In [148]:
# make a prediction
y_pred = best_grid.predict(X_test)


In [149]:
pd.crosstab(y_test,y_pred)

C:\Users\Mayer\Anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:277: FutureWarning: Categorical.ravel will return a Categorical object instead of an ndarray in a future version.
  vec = libmissing.isnaobj_old(values.ravel())


col_0         0     1
Succession           
0           754   635
1           322  3868

In [150]:
yprob = best_grid.predict_proba(X_test)
yprob = pd.DataFrame(yprob)
yprob

0         1
0     0.289474  0.710526
1     0.090909  0.909091
2     0.000000  1.000000
3     0.000000  1.000000
4     0.000000  1.000000
...        ...       ...
5574  0.000000  1.000000
5575  0.217391  0.782609
5576  0.000000  1.000000
5577  0.916667  0.083333
5578  0.000000  1.000000

[5579 rows x 2 columns]

## Saving the model

In [152]:
from sklearn.externals import joblib

filename = '7 - ActivismFinalModel.model'
joblib.dump(best_grid,filename)
             

['7 - ActivismFinalModel.model']